using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ACS.Core.Message
{
    [Serializable]
    public class MessageNode
    {
        private static long serialVersionUID = 6084300753100464527L;
        private string nodeNameOfTransportCommandId = "TRANSPORTCOMMANDID";
        private string nodeNameOfCommandId = "COMMANDID";
        private string nodeNameOfStageId = "STAGEID";
        private string nodeNameOfReplace = "REPLACE";
        private string nodeNameOfCarriers = "CARRIERS";
        private string nodeNameOfCarrierId = "CARRIERID";
        private string nodeNameOfCarrierName = "CARRIERNAME";
        private string nodeNameOfCarrier = "CARRIER";
        private string nodeNameOfCarrierLoc = "CARRIERLOC";
        private string nodeNameOfUnitInfo = "UNITINFO";
        private string nodeNameOfUnits = "UNITS";
        private string nodeNameOfUnit = "UNIT";
        private string nodeNameOfUnitName = "UNITNAME";
        private string nodeNameOfUnitId = "UNITID";
        private string xpathNameOfTransportCommandId = "/MESSAGE/DATA/TRANSPORTCOMMANDID | /MESSAGE/DATA//TRANSPORTCOMMANDID";
        private string xpathNameOfCommandId = "/MESSAGE/DATA/COMMANDID | /MESSAGE/DATA//COMMANDID";
        private string xpathNameOfStageId = "/MESSAGE/DATA/STAGEID | /MESSAGE/DATA//STAGEID";
        private string xpathNameOfReplace = "/MESSAGE/DATA/REPLACE | /MESSAGE/DATA//REPLACE";
        private string xpathNameOfExpectedDuration = "/MESSAGE/DATA/EXPECTEDDURATION | /MESSAGE/DATA//EXPECTEDDURATION";
        private string xpathNameOfDelay = "/MESSAGE/DATA/DELAY | /MESSAGE/DATA//DELAY";
        private string xpathNameOfNoBlockingTime = "/MESSAGE/DATA/NOBLOCKINGTIME | /MESSAGE/DATA//NOBLOCKINGTIME";
        private string xpathNameOfWaitTimeOut = "/MESSAGE/DATA/WAITTIMEOUT | /MESSAGE/DATA//WAITTIMEOUT";
        private string xpathNameOfCarrierId = "/MESSAGE/DATA/CARRIERID | /MESSAGE/DATA//CARRIERID";
        private string xpathNameOfCarriers = "/MESSAGE/DATA/CARRIERS | /MESSAGE/DATA//CARRIERS";
        private string xpathNameOfCarrier = "/MESSAGE/DATA/CARRIERID | /MESSAGE/DATA/CARRIERNAME | /MESSAGE/DATA//CARRIERID | /MESSAGE/DATA//CARRIERNAME";
        private string xpathNameOfCarrierName = "/MESSAGE/DATA/CARRIERNAME | /MESSAGE/DATA//CARRIERNAME";
        private string xpathNameOfCarrierLoc = "/MESSAGE/DATA/CARRIERLOC | /MESSAGE/DATA//CARRIERLOC | /MESSAGE/DATA//UNITID";
        private string xpathNameOfUnits = "/MESSAGE/DATA/UNITS";
        private string xpathNameOfUnit = "/MESSAGE/DATA/UNIT | /MESSAGE/DATA//UNIT";
        private string xpathNameOfUnitName = "/MESSAGE/DATA/UNITNAME | /MESSAGE/DATA//UNITNAME";
        private string xpathNameOfUnitId = "/MESSAGE/DATA/UNITID | /MESSAGE/DATA/STOCKERUNITID | /MESSAGE/DATA/VEHICLEID | /MESSAGE/DATA//UNITID | /MESSAGE/DATA//STOCKERUNITID | /MESSAGE/DATA//VEHICLEID";
        private string xpathNameOfCurrentUnit = "/MESSAGE/DATA//CARRIERLOC | /MESSAGE/DATA//VEHICLEID | /MESSAGE/DATA//STOCKERCRANEID";
        private string xpathNameOfEqpId = "/MESSAGE/DATA//EQPID";
        private string xpathNameOfAgvName = "/MESSAGE/DATA//AGVNAME";
        private string xpathNameOfJobType = "/MESSAGE/DATA//JOBTYPE";
        private string xpathNameOfMidLoc = "/MESSAGE/DATA//MIDLOC";
        private string xpathNameOfMidPortId = "/MESSAGE/DATA//MIDPORTID";
        private string xpathNameOfOriginLoc = "/MESSAGE/DATA//ORIGINLOC";
        private string xpathNameOfDescription = "/MESSAGE/DATA//DESCRIPTION";
        private string nodeNameOfPriority = "PRIORITY";
        private string nodeNameOfExpectedDuration = "EXPECTEDDURATION";
        private string nodeNameOfNoBlockingTime = "NOBLOCKINGTIME";
        private string nodeNameOfWaitTimeOut = "WAITTIMEOUT";
        private string nodeNameOfDelay = "DELAY";
        private string nodeNameOfLotId = "LOTID";
        private string nodeNameOfCarrierType = "CARRIERTYPE";
        private string nodeNameOfCarrierState = "CARRIERSTATE";
        private string nodeNameOfCarrierKind = "CARRIERKIND";
        private string nodeNameOfDestMachineName = "DESTMACHINENAME";
        private string nodeNameOfDestMachine = "DESTMACHINE";
        private string nodeNameOfDestUnitName = "DESTUNITNAME";
        private string nodeNameOfDestUnit = "DESTUNIT";
        private string nodeNameOfDestContainerName = "DESTCONTAINERNAME";
        private string nodeNameOfDestContainer = "DESTCONTAINER";
        private string nodeNameOfDestSlotName = "DESTSLOTNAME";
        private string nodeNameOfDestSlot = "DESTSLOT";
        private string nodeNameOfDest = "DEST";
        private string nodeNameOfSourceMachineName = "SOURCEMACHINENAME";
        private string nodeNameOfSourceMachine = "SOURCEMACHINE";
        private string nodeNameOfSourceUnit = "SOURCEUNIT";
        private string nodeNameOfSourceContainer = "SOURCECONTAINER";
        private string nodeNameOfSourceSlot = "SOURCESLOT";
        private string nodeNameOfSource = "SOURCE";
        private string nodeNameOfFromUnitName = "FROMUNITNAME";
        private string nodeNameOfToUnitName = "TOUNITNAME";
        private string nodeNameOfStockerCraneId = "STOCKERCRANEID";
        private string xpathNameOfPriority = "/MESSAGE/DATA/PRIORITY | /MESSAGE/DATA//PRIORITY";
        private string xpathNameOfLotId = "/MESSAGE/DATA/LOTID | /MESSAGE/DATA//LOTID";
        private string xpathNameOfCarrierType = "/MESSAGE/DATA/CARRIERTYPE | /MESSAGE/DATA//CARRIERTYPE | /MESSAGE/DATA//VEHICLETYPE";
        private string xpathNameOfCarrierState = "/MESSAGE/DATA/CARRIERSTATE | /MESSAGE/DATA//CARRIERSTATE";
        private string xpathNameOfCarrierKind = "/MESSAGE/DATA/CARRIERKIND";
        private string xpathNameOfSourceMachineName = "/MESSAGE/DATA//SOURCEMACHINENAME";
        private string xpathNameOfSourceMachine = "/MESSAGE/DATA//SOURCEMACHINE";
        private string xpathNameOfSourceUnit = "/MESSAGE/DATA/SOURCEUNIT | /MESSAGE/DATA//SOURCEUNIT";
        private string xpathNameOfSourceSlot = "/MESSAGE/DATA/SOURCESLOT | /MESSAGE/DATA//SOURCESLOT";
        private string xpathNameOfSource = "/MESSAGE/DATA//SOURCE | /MESSAGE/DATA//SOURCEPORT";
        private string xpathNameOfDestGroupName = "/MESSAGE/DATA//DESTGROUPNAME";
        private string xpathNameOfDestPortGroupName = "/MESSAGE/DATA//DESTPORTGROUPNAME";
        private string xpathNameOfDestMachineName = "/MESSAGE/DATA//DESTMACHINENAME";
        private string xpathNameOfDestMachine = "/MESSAGE/DATA/DESTMACHINE | /MESSAGE/DATA//DESTMACHINE";
        private string xpathNameOfDestUnitName = "/MESSAGE/DATA/DESTUNITNAME | /MESSAGE/DATA//DESTUNITNAME";
        private string xpathNameOfDestContainerName = "/MESSAGE/DATA/DESTCONTAINERNAME | /MESSAGE/DATA//DESTCONTAINERNAME";
        private string xpathNameOfDestSlotName = "/MESSAGE/DATA/DESTSLOTNAME | /MESSAGE/DATA//DESTSLOTNAME";
        private string xpathNameOfDestUnit = "/MESSAGE/DATA/DESTUNIT | /MESSAGE/DATA//DESTUNIT | /MESSAGE/DATA//DEST";
        private string xpathNameOfDest = "/MESSAGE/DATA//DEST | /MESSAGE/DATA//DESTPORT";
        private string xpathNameOfStockerCraneId = "/MESSAGE/DATA/STOCKERCRANEID | /MESSAGE/DATA//STOCKERCRANEID";
        private string nodeNameOfTransportJobId = "TRANSPORTJOBID";
        private string xpathNameOfTransportJobId = "/MESSAGE/DATA/TRANSPORTJOBID";
        private string nodeNameOfNewDestGroupName = "NEWDESTGROUPNAME";
        private string nodeNameOfNewDestMachineName = "NEWDESTMACHINENAME";
        private string nodeNameOfNewDestUnitName = "NEWDESTUNITNAME";
        private string nodeNameOfNewDestType = "NEWDESTTYPE";
        private string xpathNameOfNewDestGroupName = "/MESSAGE/DATA/NEWDESTGROUPNAME";
        private string xpathNameOfNewDestMachineName = "/MESSAGE/DATA/NEWDESTMACHINENAME";
        private string xpathNameOfNewDestUnitName = "/MESSAGE/DATA/NEWDESTUNITNAME";
        private string xpathNameOfNewDestType = "/MESSAGE/DATA/NEWDESTTYPE";
        private string nodeNameOfTransportCommandIds = "TRANSPORTCOMMANDIDS";
        private string xpathNameOfTransportCommandIds = "/MESSAGE/DATA/TRANSPORTCOMMANDIDS";
        private string nodeNameOfVehicleId = "VEHICLEID";
        private string nodeNameOfCarrierZoneName = "CARRIERZONENAME";
        private string nodeNameOfPortType = "PORTTYPE";
        private string nodeNameOfHandOffType = "HANDOFFTYPE";
        private string nodeNameOfHolded = "HOLDED";
        private string nodeNameOfContainerName = "CONTAINERNAME";
        private string nodeNameOfSlotNumber = "SLOTNUMBER";
        private string xpathNameOfVehicleId = "/MESSAGE/DATA/VEHICLEID | /MESSAGE/DATA//VEHICLEID";
        private string xpathNameOfCarrierZoneName = "/MESSAGE/DATA/CARRIERZONENAME | /MESSAGE/DATA//CARRIERZONENAME";
        private string xpathNameOfPortType = "/MESSAGE/DATA/PORTTYPE | /MESSAGE/DATA//PORTTYPE";
        private string xpathNameOfHandOffType = "/MESSAGE/DATA/HANDOFFTYPE | /MESSAGE/DATA//HANDOFFTYPE";
        private string xpathNameOfHolded = "/MESSAGE/DATA/HOLDED | /MESSAGE/DATA//HOLDED";
        private string xpathNameOfContainerName = "/MESSAGE/DATA/CONTAINERNAME | /MESSAGE/DATA//CONTAINERNAME";
        private string xpathNameOfSlotNumber = "/MESSAGE/DATA/SLOTNUMBER | /MESSAGE/DATA//SLOTNUMBER";
        private string nodeNameOfCarrierNames = "CARRIERNAMES";
        private string xpathNameOfCarrierNames = "/MESSAGE/DATA/CARRIERNAMES";
        private string nodeNameOfResultCode = "RESULTCODE";
        private string nodeNameOfNextToUnit = "NEXTTOUNIT";
        private string xpathNameOfResultCode = "/MESSAGE/DATA//RESULTCODE";
        private string xpathNameOfNextToUnit = "/MESSAGE/DATA//NEXTTOUNIT";
        private string nodeNameOfCraneState = "CRANESTATE";
        private string xpathNameOfCraneState = "/MESSAGE/DATA//CRANESTATE";
        private string nodeNameOfPortId = "PORTID";
        private string nodeNameOfPortTransferState = "PORTTRANSFERSTATE";
        private string nodeNameOfInOutType = "INOUTTYPE";
        private string nodeNameOfPortInOutType = "PORTINOUTTYPE";
        private string nodeNameOfAccessMode = "ACCESSMODE";
        private string nodeNameOfSubState = "SUBSTATE";
        private string nodeNameOfLotInfo = "LOTINFO";
        private string nodeNameOfTransferState = "TRANSFERSTATE";
        private string nodeNameOfCommandInfo = "COMMANDINFO";
        private string nodeNameOfTransferInfos = "TRANSFERINFOS";
        private string nodeNameOfTransferInfo = "TRANSFERINFO";
        private string nodeNameOfSourcePort = "SOURCEPORT";
        private string nodeNameOfDestPort = "DESTPORT";
        private string xpathNameOfPortId = "/MESSAGE/DATA/PORTID | /MESSAGE/DATA//PORTID";
        private string xpathNameOfPortTransferState = "/MESSAGE/DATA/PORTTRANSFERSTATE | /MESSAGE/DATA//PORTTRANSFERSTATE";
        private string xpathNameOfInOutType = "/MESSAGE/DATA/INOUTTYPE | /MESSAGE/DATA/PORTINOUTTYPE | /MESSAGE/DATA//INOUTTYPE | /MESSAGE/DATA//PORTINOUTTYPE";
        private string xpathNameOfPortInOutType = "/MESSAGE/DATA/PORTINOUTTYPE | /MESSAGE/DATA/INOUTTYPE | /MESSAGE/DATA//PORTINOUTTYPE | /MESSAGE/DATA//INOUTTYPE";
        private string xpathNameOfAccessMode = "/MESSAGE/DATA/*/*/*/*/ACCESSMODE | /MESSAGE/DATA//ACCESSMODE | /MESSAGE/DATA/*/*/*/*/PORTACCESSMODE | /MESSAGE/DATA//PORTACCESSMODE";
        private string xpathNameOfSubState = "/MESSAGE/DATA/SUBSTATE | /MESSAGE/DATA//SUBSTATE";
        private string xpathNameOfLotInfo = "/MESSAGE/DATA/LOTINFO | /MESSAGE/DATA//LOTINFO";
        private string nodeNameOfTransferPort = "TRANSFERPORT";
        private string nodeNameOfVehicleStatus = "VEHICLESTATUS";
        private string xpathNameOfTransferPort = "/MESSAGE/DATA//TRANSFERPORT";
        private string xpathNameOfVehicleStatus = "/MESSAGE/DATA//VEHICLESTATUS";
        private string nodeNameOfZoneName = "ZONENAME";
        private string nodeNameOfZoneCapacity = "ZONECAPACITY";
        private string xpathNameOfZoneName = "/MESSAGE/DATA//ZONENAME";
        private string xpathNameOfZoneCapacity = "/MESSAGE/DATA//ZONECAPACITY";
        private string nodeNameOfErrorId = "ERRORID";
        private string nodeNameOfErrorNumber = "ERRORNUMBER";
        private string nodeNameOfUnitState = "UNITSTATE";
        private string nodeNameOfRecoveryOptions = "RECOVERYOPTIONS";
        private string xpathNameOfErrorId = "/MESSAGE/DATA/ERRORID | /MESSAGE/DATA//ERRORID";
        private string xpathNameOfErrorNumber = "/MESSAGE/DATA/ERRORNUMBER | /MESSAGE/DATA//ERRORNUMBER";
        private string xpathNameOfUnitState = "/MESSAGE/DATA/UNITSTATE | MESSAGE/DATA/STOCKERUNITSTATE | MESSAGE/DATA/VEHICLESTATE | /MESSAGE/DATA//UNITSTATE | MESSAGE/DATA//STOCKERUNITSTATE | MESSAGE/DATA//VEHICLESTATE";
        private string xpathNameOfRecoveryOptions = "/MESSAGE/DATA/RECOVERYOPTIONS | /MESSAGE/DATA//RECOVERYOPTIONS";
        private string nodeNameOfAlarmCode = "ALARMCODE";
        private string nodeNameOfAlarmId = "ALARMID";
        private string nodeNameOfAlarmText = "ALARMTEXT";
        private string xpathNameOfAlarmCode = "/MESSAGE/DATA//ALARMCODE | /MESSAGE/DATA//ALCD";
        private string xpathNameOfAlarmId = "/MESSAGE/DATA//ALARMID | /MESSAGE/DATA//ALID";
        private string xpathNameOfAlarmText = "/MESSAGE/DATA//ALARMTEXT | /MESSAGE/DATA//ALTX";
        private string nodeNameOfCurrentUnitPosition = "CURRENTUNITPOSITION";
        private string nodeNameOfUnitStateClearable = "UNITSTATECLEARABLE";
        private string xpathNameOfCurrentUnitPosition = "/MESSAGE/DATA//CURRENTUNITPOSITION";
        private string xpathNameOfUnitStateClearable = "/MESSAGE/DATA//UNITSTATECLEARABLE";
        private string nodeNameOfIdReadState = "IDREADSTATUS";
        private string xpathNameOfIdReadState = "/MESSAGE/DATA//IDREADSTATUS";
        private string nodeNameOfTerminalId = "TERMINALID";
        private string nodeNameOfInformation = "INFORMATION";
        private string xpathNameOfTerminalId = "/MESSAGE/DATA//TERMINALID";
        private string xpathNameOfInformation = "/MESSAGE/DATA//INFORMATION";
        private string nodeNameOfCommandType = "COMMANDTYPE";
        private string xpathNameOfCommandType = "/MESSAGE/DATA//COMMANDTYPE";
        private string nodeNameOfPnpId = "PNPID";
        private string xpathNameOfPnpId = "/MESSAGE/DATA//PNPID";
        private string nodeNameOfShuttleId = "SHUTTLEID";
        private string nodeNameOfLocation = "LOCATION";
        private string xpathNameOfShuttleId = "/MESSAGE/DATA//SHUTTLEID";
        private string xpathNameOfLocation = "/MESSAGE/DATA//LOCATION";
        private string nodeNameOfTscState = "TSCSTATE";
        private string xpathNameOfTscState = "/MESSAGE/DATA//TSCSTATE";
        private string nodeNameOfControlState = "CONTROLSTATE";
        private string xpathNameOfControlState = "/MESSAGE/DATA//CONTROLSTATE";
        private string nodeNameOfEnhancedActiveZones = "ENHANCEDACTIVEZONES";
        private string nodeNameOfEnhancedActiveZonesZoneName = "ZONENAME";
        private string nodeNameOfEnhancedActiveZonesZoneCapacity = "ZONECAPACITY";
        private string nodeNameOfEnhancedActiveZonesZoneSize = "ZONESIZE";
        private string nodeNameOfEnhancedActiveZonesZoneType = "ZONETYPE";
        private string xpathNameOfEnhancedActiveZones = "/MESSAGE/DATA/*/*/ENHANCEDACTIVEZONES | /MESSAGE/DATA//ENHANCEDACTIVEZONES";
        private string xpathNameOfEnhancedActiveZonesZoneName = "/MESSAGE/DATA//ENHANCEDACTIVEZONES/*/ZONENAME";
        private string xpathNameOfEnhancedActiveZonesZoneCapacity = "/MESSAGE/DATA//ENHANCEDACTIVEZONES/*/ZONECAPACITY";
        private string xpathNameOfEnhancedActiveZonesZoneSize = "/MESSAGE/DATA//ENHANCEDACTIVEZONES/*/ZONESIZE";
        private string xpathNameOfEnhancedActiveZonesZoneType = "/MESSAGE/DATA//ENHANCEDACTIVEZONES/*/ZONETYPE";
        private string nodeNameOfEnhancedAlarmsAlarmSet = "ALARMSET";
        private string nodeNameOfEnhancedAlarmsAlarmId = "ALARMID";
        private string nodeNameOfEnhancedAlarmsAlarmCode = "ALARMCODE";
        private string nodeNameOfEnhancedAlarmsAlarmText = "ALARMTEXT";
        private string xpathNameOfEnhancedAlarmsAlarmSet = "/MESSAGE/DATA/*/*/ALARMSET | /MESSAGE/DATA//ALARMSET | /MESSAGE/DATA/*/*/ALARMSSET | /MESSAGE/DATA//ALARMSSET";
        private string xpathNameOfEnhancedAlarmsAlarmId = "/MESSAGE/DATA/*/*/ENHANCEDALARMS/ALARMID | /MESSAGE/DATA/*/*/ENHANCEDALARMS/*/ALARMID | /MESSAGE/DATA//ALID";
        private string xpathNameOfEnhancedAlarmsAlarmCode = "/MESSAGE/DATA/*/*/ENHANCEDALARMS/ALARMCODE | /MESSAGE/DATA/*/*/ENHANCEDALARMS/*/ALARMCODE";
        private string xpathNameOfEnhancedAlarmsAlarmText = "/MESSAGE/DATA/*/*/ENHANCEDALARMS/ALARMTEXT | /MESSAGE/DATA/*/*/ENHANCEDALARMS/*/ALARMTEXT";
        private string nodeNameOfEnhancedUnitAlarms = "ENHANCEDUNITALARMS";
        private string nodeNameOfEnhancedUnitAlarmsUnitId = "UNITID";
        private string nodeNameOfEnhancedUnitAlarmsAlarmId = "ALARMID";
        private string nodeNameOfEnhancedUnitAlarmsAlarmCode = "ALARMCODE";
        private string nodeNameOfEnhancedUnitAlarmsAlarmText = "ALARMTEXT";
        private string nodeNameOfEnhancedUnitAlarmsCurrentUnitPosition = "CURRENTUNITPOSITION";
        private string nodeNameOfEnhancedUnitAlarmsUnitStateClearable = "UNITSTATECLEARABLE";
        private string xpathNameOfEnhancedUnitAlarms = "/MESSAGE/DATA/*/*/ENHANCEDUNITALARMS | /MESSAGE/DATA//ENHANCEDUNITALARMS";
        private string xpathNameOfEnhancedUnitAlarmsUnitId = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/UNITID";
        private string xpathNameOfEnhancedUnitAlarmsAlarmId = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/ALARMID";
        private string xpathNameOfEnhancedUnitAlarmsAlarmCode = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/ALARMCODE";
        private string xpathNameOfEnhancedUnitAlarmsAlarmText = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/ALARMTEXT";
        private string xpathNameOfEnhancedUnitAlarmsCurrentUnitPosition = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/CURRENTUNITPOSITION";
        private string xpathNameOfEnhancedUnitAlarmsUnitStateClearable = "/MESSAGE/DATA//ENHANCEDUNITALARMS/*/UNITSTATECLEARABLE";
        private string nodeNameOfEnhancedCarriers = "ENHANCEDCARRIERS";
        private string nodeNameOfEnhancedCarriersCarrierId = "CARRIERID";
        private string nodeNameOfEnhancedCarriersVehicleId = "VEHICLEID";
        private string nodeNameOfEnhancedCarriersCarrierLoc = "CARRIERLOC";
        private string nodeNameOfEnhancedCarriersInstallTime = "INSTALLTIME";
        private string nodeNameOfEnhancedCarriersCarrierZoneName = "CARRIERZONENAME";
        private string nodeNameOfEnhancedCarriersCarrierState = "CARRIERSTATE";
        private string nodeNameOfEnhancedCarriersCarrierType = "CARRIERTYPE";
        private string xpathNameOfEnhancedCarriers = "/MESSAGE/DATA/*/*/ENHANCEDCARRIERS | /MESSAGE/DATA/*/ENHANCEDCARRIERS | /MESSAGE/DATA//ENHANCEDCARRIERS";
        private string xpathNameOfEnhancedCarriersCarrierId = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/CARRIERID";
        private string xpathNameOfEnhancedCarriersVehicleId = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/VEHICLEID";
        private string xpathNameOfEnhancedCarriersCarrierLoc = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/CARRIERLOC";
        private string xpathNameOfEnhancedCarriersInstallTime = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/INSTALLTIME";
        private string xpathNameOfEnhancedCarriersCarrierZoneName = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/CARRIERZONENAME";
        private string xpathNameOfEnhancedCarriersCarrierState = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/CARRIERSTATE";
        private string xpathNameOfEnhancedCarriersCarrierType = "/MESSAGE/DATA//ENHANCEDCARRIERS/*/CARRIERTYPE";
        private string nodeNameOfEnhancedTransfers = "ENHANCEDTRANSFERS";
        private string nodeNameOfEnhancedTransfersCommandInfo = "COMMANDINFO";
        private string nodeNameOfEnhancedTransfersTransferInfo = "TRANSFERINFO";
        private string nodeNameOfEnhancedTransfersTransferState = "TRANSFERSTATE";
        private string nodeNameOfEnhancedTransfersCommandId = "COMMANDID";
        private string nodeNameOfEnhancedTransfersPriority = "PRIORITY";
        private string nodeNameOfEnhancedTransfersReplace = "REPLACE";
        private string nodeNameOfEnhancedTransfersCarrierId = "CARRIERID";
        private string nodeNameOfEnhancedTransfersCarrierLoc = "CARRIERLOC";
        private string nodeNameOfEnhancedTransfersSource = "SOURCE";
        private string nodeNameOfEnhancedTransfersDest = "DEST";
        private string nodeNameOfEnhancedTransfersSourcePort = "SOURCEPORT";
        private string nodeNameOfEnhancedTransfersDestPort = "DESTPORT";
        private string xpathNameOfEnhancedTransfers = "/MESSAGE/DATA/*/*/ENHANCEDTRANSFERS | /MESSAGE/DATA//ENHANCEDTRANSFERS";
        private string xpathNameOfEnhancedTransfersTransferState = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/TRANSFERSTATE";
        private string xpathNameOfEnhancedTransfersCommandId = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/COMMANDID";
        private string xpathNameOfEnhancedTransfersPriority = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/PRIORITY";
        private string xpathNameOfEnhancedTransfersReplace = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/REPLACE";
        private string xpathNameOfEnhancedTransfersCarrierId = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/*/CARRIERID | /MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/CARRIERID";
        private string xpathNameOfEnhancedTransfersSource = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/*/SOURCE | /MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/*/SOURCEPORT | /MESSAGE/DATA/*/*/ENHANCEDTRANSFERS/*/*/CARRIERLOC";
        private string xpathNameOfEnhancedTransfersDest = "/MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/*/DEST | /MESSAGE/DATA//ENHANCEDTRANSFERS/*/*/*/DESTPORT | /MESSAGE/DATA/*/*/ENHANCEDTRANSFERS/*/*/DEST";
        private string nodeNameOfEnhancedVehicles = "ENHANCEDVEHICLES";
        private string nodeNameOfEnhancedVehiclesVehicleId = "VEHICLEID";
        private string nodeNameOfEnhancedVehiclesVehicleState = "VEHICLESTATE";
        private string nodeNameOfEnhancedVehiclesVehicleStatus = "VEHICLESTATUS";
        private string nodeNameOfEnhancedVehiclesVehicleLocation = "VEHICLELOCATION";
        private string xpathNameOfEnhancedVehicles = "/MESSAGE/DATA/*/*/ENHANCEDVEHICLES | /MESSAGE/DATA//ENHANCEDVEHICLES";
        private string xpathNameOfEnhancedVehiclesVehicleId = "/MESSAGE/DATA//ENHANCEDVEHICLES/*/VEHICLEID | /MESSAGE/DATA//ENHANCEDVEHICLES//VEHICLEID";
        private string xpathNameOfEnhancedVehiclesVehicleState = "/MESSAGE/DATA//ENHANCEDVEHICLES/*/VEHICLESTATE | /MESSAGE/DATA//ENHANCEDVEHICLES//VEHICLESTATE";
        private string xpathNameOfEnhancedVehiclesVehicleStatus = "/MESSAGE/DATA//ENHANCEDVEHICLES/*/VEHICLESTATUS | /MESSAGE/DATA//ENHANCEDVEHICLES//VEHICLESTATUS";
        private string xpathNameOfEnhancedVehiclesVehicleLocation = "/MESSAGE/DATA//ENHANCEDVEHICLES/*/VEHICLELOCATION | /MESSAGE/DATA//ENHANCEDVEHICLES//VEHICLELOCATION";
        private string nodeNameOfEnhancedPorts = "ENHANCEDPORTS";
        private string nodeNameOfEnhancedPortsPortId = "PORTID";
        private string nodeNameOfEnhancedPortsState = "STATE";
        private string nodeNameOfEnhancedPortsPortTransferState = "PORTTRANSFERSTATE";
        private string nodeNameOfEnhancedPortsSubState = "SUBSTATE";
        private string nodeNameOfEnhancedPortsPortAccessMode = "PORTACCESSMODE";
        private string nodeNameOfEnhancedPortsPortInOutType = "PORTINOUTTYPE";
        private string nodeNameOfEnhancedPortsPortProcessingState = "PORTPROCESSINGSTATE";
        private string nodeNameOfEnhancedportsUseRfReader = "IDREADER";
        private string xpathNameOfEnhancedPorts = "/MESSAGE/DATA/*/*/ENHANCEDPORTS | /MESSAGE/DATA//ENHANCEDPORTS | /MESSAGE/DATA/*/*/CURRENTPORTSTATES | /MESSAGE/DATA//CURRENTPORTSTATES";
        private string xpathNameOfEnhancedPortsPortId = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/PORTID | /MESSAGE/DATA//ENHANCEDPORTS/*/PORTID | /MESSAGE/DATA//ENHANCEDPORTS//PORTID";
        private string xpathNameOfEnhancedPortsState = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/STATE | /MESSAGE/DATA/*/*/ENHANCEDPORTS//STATE";
        private string xpathNameOfEnhancedPortsPortTransferState = "/MESSAGE/DATA/*/ENHANCEDPORTS/*/PORTTRANSFERSTATE | /MESSAGE/DATA/*/ENHANCEDPORTS//PORTTRANSFERSTATE";
        private string xpathNameOfEnhancedPortsSubState = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/SUBSTATE | /MESSAGE/DATA/*/*/ENHANCEDPORTS//SUBSTATE";
        private string xpathNameOfEnhancedPortsPortAccessMode = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/PORTACCESSMODE | /MESSAGE/DATA/*/*/ENHANCEDPORTS//PORTACCESSMODE";
        private string xpathNameOfEnhancedPortsPortInOutType = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/PORTINOUTTYPE | /MESSAGE/DATA/*/*/ENHANCEDPORTS//PORTINOUTTYPE";
        private string xpathNameOfEnhancedPortsPortProcessingState = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/PORTPROCESSINGSTATE | /MESSAGE/DATA/*/*/ENHANCEDPORTS//PORTPROCESSINGSTATE";
        private string xpathNameOfEnhancedPortsUseRfReader = "/MESSAGE/DATA/*/*/ENHANCEDPORTS/*/IDREADER | /MESSAGE/DATA/*/*/ENHANCEDPORTS//IDREADER";
        private string nodeNameOfEnhancedShelves = "ENHANCEDSHELVES";
        private string nodeNameOfEnhancedShelvesShelfName = "SHELFNAME";
        private string nodeNameOfEnhancedShelvesShelfState = "SHELFSTATE";
        private string nodeNameOfEnhancedShelvesShelfStatus = "SHELFSTATUS";
        private string xpathNameOfEnhancedShelves = "/MESSAGE/DATA/*/*/ENHANCEDSHELVES | /MESSAGE/DATA//ENHANCEDSHELVES";
        private string xpathNameOfEnhancedShelvesShelfName = "/MESSAGE/DATA//ENHANCEDSHELVES/*/SHELFNAME";
        private string xpathNameOfEnhancedShelvesShelfState = "/MESSAGE/DATA//ENHANCEDSHELVES/*/SHELFSTATE";
        private string xpathNameOfEnhancedShelvesShelfStatus = "/MESSAGE/DATA//ENHANCEDSHELVES/*/SHELFSTATUS";
        private string nodeNameOfEnhancedShuttles = "ENHANCEDSHUTTLES";
        private string nodeNameOfEnhancedShuttlesLifterName = "LIFTERNAME";
        private string nodeNameOfEnhancedShuttlesShuttleName = "SHUTTLEID";
        private string nodeNameOfEnhancedShuttlesLocation = "LOCATIONID";
        private string nodeNameOfEnhancedShuttlesShuttleState = "SHUTTLESTATE";
        private string xpathNameOfEnhancedShuttles = "/MESSAGE/DATA/*/ENHANCEDSHUTTLES | /MESSAGE/DATA//ENHANCEDSHUTTLES";
        private string xpathNameOfEnhancedShuttlesLifterName = "/MESSAGE/DATA//ENHANCEDSHUTTLES/*/LIFTERNAME | /MESSAGE/DATA//ENHANCEDSHUTTLES//LIFTERNAME";
        private string xpathNameOfEnhancedShuttlesShuttleName = "/MESSAGE/DATA//ENHANCEDSHUTTLES/*/SHUTTLEID | /MESSAGE/DATA//ENHANCEDSHUTTLES//SHUTTLEID";
        private string xpathNameOfEnhancedShuttlesLocation = "/MESSAGE/DATA//ENHANCEDSHUTTLES/*/LOCATIONID | /MESSAGE/DATA//ENHANCEDSHUTTLES//LOCATIONID";
        private string xpathNameOfEnhancedShuttlesShuttleState = "/MESSAGE/DATA//ENHANCEDSHUTTLES/*/SHUTTLESTATE | /MESSAGE/DATA//ENHANCEDSHUTTLES//SHUTTLESTATE";
        private string nodeNameOfCurrentPortTransferStates = "CURRENTPORTSTATES";
        private string nodeNameOfCurrentPortTransferStatesPortInfo = "PORTINFO";
        private string nodeNameOfCurrentPortTransferStatesPortInfoPortId = "PORTID";
        private string nodeNameOfCurrentPortTransferStatesPortInfoPortTransferState = "PORTTRANSFERSTATE";
        private string xpathNameOfCurrentPortTransferStates = "/MESSAGE/DATA//CURRENTPORTSTATES";
        private string xpathNameOfCurrentPortTransferStatesPortInfo = "/MESSAGE/DATA//CURRENTPORTSTATES/PORTINFO";
        private string xpathNameOfCurrentPortTransferStatesPortInfoPortId = "/MESSAGE/DATA//PORTINFO/PORTID";
        private string xpathNameOfCurrentPortTransferStatesPortInfoPortTransferState = "/MESSAGE/DATA//PORTINFO/PORTTRANSFERSTATE";
        private string nodeNameOfEnhancedControlState = "CONTROLSTATE";
        private string xpathNameOfEnhancedControlState = "/MESSAGE/DATA/*/*/CONTROLSTATE | /MESSAGE/DATA//CONTROLSTATE";
        private string nodeNameOfEnhancedCraneStates = "ENHANCEDCRANESTATES";
        private string nodeNameOfEnhancedCraneStatesStockerCraneId = "STOCKERCRANEID";
        private string nodeNameOfEnhancedCraneStatesCraneState = "CRANESTATE";
        private string xpathNameOfEnhancedCraneStates = "/MESSAGE/DATA/*/*/ENHANCEDCRANESTATES | /MESSAGE/DATA//ENHANCEDCRANESTATES";
        private string xpathNameOfEnhancedCraneStatesStockerCraneId = "/MESSAGE/DATA/*/*/ENHANCEDCRANESTATES/STOCKERCRANEID | /MESSAGE/DATA/*/*/ENHANCEDCRANESTATES/*/STOCKERCRANEID";
        private string xpathNameOfEnhancedCraneStatesCraneState = "/MESSAGE/DATA/*/*/ENHANCEDCRANESTATES/CRANESTATE | /MESSAGE/DATA/*/*/ENHANCEDCRANESTATES/*/CRANESTATE";
        private string nodeNameOfEnhancedStockerStatus = "STOCKERSTATUS";
        private string nodeNameOfEnhancedStockerStatusMachineName = "EQPNAME";
        private string nodeNameOfEnhancedStockerStatusStockerState = "STOCKERSTATE";
        private string xpathNameOfEnhancedStockerStatus = "/MESSAGE/DATA/*/STOCKERSTATUS | /MESSAGE/DATA//STOCKERSTATUS | /MESSAGE/DATA//ENHANCEDSTOCKERSTATUS";
        private string xpathNameOfEnhancedStockerStatusMachineName = "/MESSAGE/DATA//STOCKERSTATUS/EQPNAME";
        private string xpathNameOfEnhancedStockerStatusStockerState = "/MESSAGE/DATA//STOCKERSTATUS/STOCKERSTATE";

        public string NodeNameOfTransportCommandId { get { return nodeNameOfTransportCommandId; } set { nodeNameOfTransportCommandId = value; } }
        public string NodeNameOfCommandId { get { return nodeNameOfCommandId; } set { nodeNameOfCommandId = value; } }
        public string NodeNameOfStageId { get { return nodeNameOfStageId; } set { nodeNameOfStageId = value; } }
        public string NodeNameOfReplace { get { return nodeNameOfReplace; } set { nodeNameOfReplace = value; } }
        public string NodeNameOfCarriers { get { return nodeNameOfCarriers; } set { nodeNameOfCarriers = value; } }
        public string NodeNameOfCarrierId { get { return nodeNameOfCarrierId; } set { nodeNameOfCarrierId = value; } }
        public string NodeNameOfCarrierName { get { return nodeNameOfCarrierName; } set { nodeNameOfCarrierName = value; } }
        public string NodeNameOfCarrier { get { return nodeNameOfCarrier; } set { nodeNameOfCarrier = value; } }
        public string NodeNameOfCarrierLoc { get { return nodeNameOfCarrierLoc; } set { nodeNameOfCarrierLoc = value; } }
        public string NodeNameOfUnitInfo { get { return nodeNameOfUnitInfo; } set { nodeNameOfUnitInfo = value; } }
        public string NodeNameOfUnits { get { return nodeNameOfUnits; } set { nodeNameOfUnits = value; } }
        public string NodeNameOfUnit { get { return nodeNameOfUnit; } set { nodeNameOfUnit = value; } }
        public string NodeNameOfUnitName { get { return nodeNameOfUnitName; } set { nodeNameOfUnitName = value; } }
        public string NodeNameOfUnitId { get { return nodeNameOfUnitId; } set { nodeNameOfUnitId = value; } }
        public string XpathNameOfTransportCommandId { get { return xpathNameOfTransportCommandId; } set { xpathNameOfTransportCommandId = value; } }
        public string XpathNameOfCommandId { get { return xpathNameOfCommandId; } set { xpathNameOfCommandId = value; } }
        public string XpathNameOfStageId { get { return xpathNameOfStageId; } set { xpathNameOfStageId = value; } }
        public string XpathNameOfReplace { get { return xpathNameOfReplace; } set { xpathNameOfReplace = value; } }
        public string XpathNameOfExpectedDuration { get { return xpathNameOfExpectedDuration; } set { xpathNameOfExpectedDuration = value; } }
        public string XpathNameOfDelay { get { return xpathNameOfDelay; } set { xpathNameOfDelay = value; } }
        public string XpathNameOfNoBlockingTime { get { return xpathNameOfNoBlockingTime; } set { xpathNameOfNoBlockingTime = value; } }
        public string XpathNameOfWaitTimeOut { get { return xpathNameOfWaitTimeOut; } set { xpathNameOfWaitTimeOut = value; } }
        public string XpathNameOfCarrierId { get { return xpathNameOfCarrierId; } set { xpathNameOfCarrierId = value; } }
        public string XpathNameOfCarriers { get { return xpathNameOfCarriers; } set { xpathNameOfCarriers = value; } }
        public string XpathNameOfCarrier { get { return xpathNameOfCarrier; } set { xpathNameOfCarrier = value; } }
        public string XpathNameOfCarrierName { get { return xpathNameOfCarrierName; } set { xpathNameOfCarrierName = value; } }
        public string XpathNameOfCarrierLoc { get { return xpathNameOfCarrierLoc; } set { xpathNameOfCarrierLoc = value; } }
        public string XpathNameOfUnits { get { return xpathNameOfUnits; } set { xpathNameOfUnits = value; } }
        public string XpathNameOfUnit { get { return xpathNameOfUnit; } set { xpathNameOfUnit = value; } }
        public string XpathNameOfUnitName { get { return xpathNameOfUnitName; } set { xpathNameOfUnitName = value; } }
        public string XpathNameOfUnitId { get { return xpathNameOfUnitId; } set { xpathNameOfUnitId = value; } }
        public string XpathNameOfCurrentUnit { get { return xpathNameOfCurrentUnit; } set { xpathNameOfCurrentUnit = value; } }
        public string XpathNameOfEqpId { get { return xpathNameOfEqpId; } set { xpathNameOfEqpId = value; } }
        public string XpathNameOfAgvName { get { return xpathNameOfAgvName; } set { xpathNameOfAgvName = value; } }
        public string XpathNameOfJobType { get { return xpathNameOfJobType; } set { xpathNameOfJobType = value; } }
        public string XpathNameOfMidLoc { get { return xpathNameOfMidLoc; } set { xpathNameOfMidLoc = value; } }
        public string XpathNameOfMidPortId { get { return xpathNameOfMidPortId; } set { xpathNameOfMidPortId = value; } }
        public string XpathNameOfOriginLoc { get { return xpathNameOfOriginLoc; } set { xpathNameOfOriginLoc = value; } }
        public string XpathNameOfDescription { get { return xpathNameOfDescription; } set { xpathNameOfDescription = value; } }
        public string NodeNameOfPriority { get { return nodeNameOfPriority; } set { nodeNameOfPriority = value; } }
        public string NodeNameOfExpectedDuration { get { return nodeNameOfExpectedDuration; } set { nodeNameOfExpectedDuration = value; } }
        public string NodeNameOfNoBlockingTime { get { return nodeNameOfNoBlockingTime; } set { nodeNameOfNoBlockingTime = value; } }
        public string NodeNameOfWaitTimeOut { get { return nodeNameOfWaitTimeOut; } set { nodeNameOfWaitTimeOut = value; } }
        public string NodeNameOfDelay { get { return nodeNameOfDelay; } set { nodeNameOfDelay = value; } }
        public string NodeNameOfLotId { get { return nodeNameOfLotId; } set { nodeNameOfLotId = value; } }
        public string NodeNameOfCarrierType { get { return nodeNameOfCarrierType; } set { nodeNameOfCarrierType = value; } }
        public string NodeNameOfCarrierState { get { return nodeNameOfCarrierState; } set { nodeNameOfCarrierState = value; } }
        public string NodeNameOfCarrierKind { get { return nodeNameOfCarrierKind; } set { nodeNameOfCarrierKind = value; } }
        public string NodeNameOfDestMachineName { get { return nodeNameOfDestMachineName; } set { nodeNameOfDestMachineName = value; } }
        public string NodeNameOfDestMachine { get { return nodeNameOfDestMachine; } set { nodeNameOfDestMachine = value; } }
        public string NodeNameOfDestUnitName { get { return nodeNameOfDestUnitName; } set { nodeNameOfDestUnitName = value; } }
        public string NodeNameOfDestUnit { get { return nodeNameOfDestUnit; } set { nodeNameOfDestUnit = value; } }
        public string NodeNameOfDestContainerName { get { return nodeNameOfDestContainerName; } set { nodeNameOfDestContainerName = value; } }
        public string NodeNameOfDestContainer { get { return nodeNameOfDestContainer; } set { nodeNameOfDestContainer = value; } }
        public string NodeNameOfDestSlotName { get { return nodeNameOfDestSlotName; } set { nodeNameOfDestSlotName = value; } }
        public string NodeNameOfDestSlot { get { return nodeNameOfDestSlot; } set { nodeNameOfDestSlot = value; } }
        public string NodeNameOfDest { get { return nodeNameOfDest; } set { nodeNameOfDest = value; } }
        public string NodeNameOfSourceMachineName { get { return nodeNameOfSourceMachineName; } set { nodeNameOfSourceMachineName = value; } }
        public string NodeNameOfSourceMachine { get { return nodeNameOfSourceMachine; } set { nodeNameOfSourceMachine = value; } }
        public string NodeNameOfSourceUnit { get { return nodeNameOfSourceUnit; } set { nodeNameOfSourceUnit = value; } }
        public string NodeNameOfSourceContainer { get { return nodeNameOfSourceContainer; } set { nodeNameOfSourceContainer = value; } }
        public string NodeNameOfSourceSlot { get { return nodeNameOfSourceSlot; } set { nodeNameOfSourceSlot = value; } }
        public string NodeNameOfSource { get { return nodeNameOfSource; } set { nodeNameOfSource = value; } }
        public string NodeNameOfFromUnitName { get { return nodeNameOfFromUnitName; } set { nodeNameOfFromUnitName = value; } }
        public string NodeNameOfToUnitName { get { return nodeNameOfToUnitName; } set { nodeNameOfToUnitName = value; } }
        public string NodeNameOfStockerCraneId { get { return nodeNameOfStockerCraneId; } set { nodeNameOfStockerCraneId = value; } }
        public string XpathNameOfPriority { get { return xpathNameOfPriority; } set { xpathNameOfPriority = value; } }
        public string XpathNameOfLotId { get { return xpathNameOfLotId; } set { xpathNameOfLotId = value; } }
        public string XpathNameOfCarrierType { get { return xpathNameOfCarrierType; } set { xpathNameOfCarrierType = value; } }
        public string XpathNameOfCarrierState { get { return xpathNameOfCarrierState; } set { xpathNameOfCarrierState = value; } }
        public string XpathNameOfCarrierKind { get { return xpathNameOfCarrierKind; } set { xpathNameOfCarrierKind = value; } }
        public string XpathNameOfSourceMachineName { get { return xpathNameOfSourceMachineName; } set { xpathNameOfSourceMachineName = value; } }
        public string XpathNameOfSourceMachine { get { return xpathNameOfSourceMachine; } set { xpathNameOfSourceMachine = value; } }
        public string XpathNameOfSourceUnit { get { return xpathNameOfSourceUnit; } set { xpathNameOfSourceUnit = value; } }
        public string XpathNameOfSourceSlot { get { return xpathNameOfSourceSlot; } set { xpathNameOfSourceSlot = value; } }
        public string XpathNameOfSource { get { return xpathNameOfSource; } set { xpathNameOfSource = value; } }
        public string XpathNameOfDestGroupName { get { return xpathNameOfDestGroupName; } set { xpathNameOfDestGroupName = value; } }
        public string XpathNameOfDestPortGroupName { get { return xpathNameOfDestPortGroupName; } set { xpathNameOfDestPortGroupName = value; } }
        public string XpathNameOfDestMachineName { get { return xpathNameOfDestMachineName; } set { xpathNameOfDestMachineName = value; } }
        public string XpathNameOfDestMachine { get { return xpathNameOfDestMachine; } set { xpathNameOfDestMachine = value; } }
        public string XpathNameOfDestUnitName { get { return xpathNameOfDestUnitName; } set { xpathNameOfDestUnitName = value; } }
        public string XpathNameOfDestContainerName { get { return xpathNameOfDestContainerName; } set { xpathNameOfDestContainerName = value; } }
        public string XpathNameOfDestSlotName { get { return xpathNameOfDestSlotName; } set { xpathNameOfDestSlotName = value; } }
        public string XpathNameOfDestUnit { get { return xpathNameOfDestUnit; } set { xpathNameOfDestUnit = value; } }
        public string XpathNameOfDest { get { return xpathNameOfDest; } set { xpathNameOfDest = value; } }
        public string XpathNameOfStockerCraneId { get { return xpathNameOfStockerCraneId; } set { xpathNameOfStockerCraneId = value; } }
        public string NodeNameOfTransportJobId { get { return nodeNameOfTransportJobId; } set { nodeNameOfTransportJobId = value; } }
        public string XpathNameOfTransportJobId { get { return xpathNameOfTransportJobId; } set { xpathNameOfTransportJobId = value; } }
        public string NodeNameOfNewDestGroupName { get { return nodeNameOfNewDestGroupName; } set { nodeNameOfNewDestGroupName = value; } }
        public string NodeNameOfNewDestMachineName { get { return nodeNameOfNewDestMachineName; } set { nodeNameOfNewDestMachineName = value; } }
        public string NodeNameOfNewDestUnitName { get { return nodeNameOfNewDestUnitName; } set { nodeNameOfNewDestUnitName = value; } }
        public string NodeNameOfNewDestType { get { return nodeNameOfNewDestType; } set { nodeNameOfNewDestType = value; } }
        public string XpathNameOfNewDestGroupName { get { return xpathNameOfNewDestGroupName; } set { xpathNameOfNewDestGroupName = value; } }
        public string XpathNameOfNewDestMachineName { get { return xpathNameOfNewDestMachineName; } set { xpathNameOfNewDestMachineName = value; } }
        public string XpathNameOfNewDestUnitName { get { return xpathNameOfNewDestUnitName; } set { xpathNameOfNewDestUnitName = value; } }
        public string XpathNameOfNewDestType { get { return xpathNameOfNewDestType; } set { xpathNameOfNewDestType = value; } }
        public string NodeNameOfTransportCommandIds { get { return nodeNameOfTransportCommandIds; } set { nodeNameOfTransportCommandIds = value; } }
        public string XpathNameOfTransportCommandIds { get { return xpathNameOfTransportCommandIds; } set { xpathNameOfTransportCommandIds = value; } }
        public string NodeNameOfVehicleId { get { return nodeNameOfVehicleId; } set { nodeNameOfVehicleId = value; } }
        public string NodeNameOfCarrierZoneName { get { return nodeNameOfCarrierZoneName; } set { nodeNameOfCarrierZoneName = value; } }
        public string NodeNameOfPortType { get { return nodeNameOfPortType; } set { nodeNameOfPortType = value; } }
        public string NodeNameOfHandOffType { get { return nodeNameOfHandOffType; } set { nodeNameOfHandOffType = value; } }
        public string NodeNameOfHolded { get { return nodeNameOfHolded; } set { nodeNameOfHolded = value; } }
        public string NodeNameOfContainerName { get { return nodeNameOfContainerName; } set { nodeNameOfContainerName = value; } }
        public string NodeNameOfSlotNumber { get { return nodeNameOfSlotNumber; } set { nodeNameOfSlotNumber = value; } }
        public string XpathNameOfVehicleId { get { return xpathNameOfVehicleId; } set { xpathNameOfVehicleId = value; } }
        public string XpathNameOfCarrierZoneName { get { return xpathNameOfCarrierZoneName; } set { xpathNameOfCarrierZoneName = value; } }
        public string XpathNameOfPortType { get { return xpathNameOfPortType; } set { xpathNameOfPortType = value; } }
        public string XpathNameOfHandOffType { get { return xpathNameOfHandOffType; } set { xpathNameOfHandOffType = value; } }
        public string XpathNameOfHolded { get { return xpathNameOfHolded; } set { xpathNameOfHolded = value; } }
        public string XpathNameOfContainerName { get { return xpathNameOfContainerName; } set { xpathNameOfContainerName = value; } }
        public string XpathNameOfSlotNumber { get { return xpathNameOfSlotNumber; } set { xpathNameOfSlotNumber = value; } }
        public string NodeNameOfCarrierNames { get { return nodeNameOfCarrierNames; } set { nodeNameOfCarrierNames = value; } }
        public string XpathNameOfCarrierNames { get { return xpathNameOfCarrierNames; } set { xpathNameOfCarrierNames = value; } }
        public string NodeNameOfResultCode { get { return nodeNameOfResultCode; } set { nodeNameOfResultCode = value; } }
        public string NodeNameOfNextToUnit { get { return nodeNameOfNextToUnit; } set { nodeNameOfNextToUnit = value; } }
        public string XpathNameOfResultCode { get { return xpathNameOfResultCode; } set { xpathNameOfResultCode = value; } }
        public string XpathNameOfNextToUnit { get { return xpathNameOfNextToUnit; } set { xpathNameOfNextToUnit = value; } }
        public string NodeNameOfCraneState { get { return nodeNameOfCraneState; } set { nodeNameOfCraneState = value; } }
        public string XpathNameOfCraneState { get { return xpathNameOfCraneState; } set { xpathNameOfCraneState = value; } }
        public string NodeNameOfPortId { get { return nodeNameOfPortId; } set { nodeNameOfPortId = value; } }
        public string NodeNameOfPortTransferState { get { return nodeNameOfPortTransferState; } set { nodeNameOfPortTransferState = value; } }
        public string NodeNameOfInOutType { get { return nodeNameOfInOutType; } set { nodeNameOfInOutType = value; } }
        public string NodeNameOfPortInOutType { get { return nodeNameOfPortInOutType; } set { nodeNameOfPortInOutType = value; } }
        public string NodeNameOfAccessMode { get { return nodeNameOfAccessMode; } set { nodeNameOfAccessMode = value; } }
        public string NodeNameOfSubState { get { return nodeNameOfSubState; } set { nodeNameOfSubState = value; } }
        public string NodeNameOfLotInfo { get { return nodeNameOfLotInfo; } set { nodeNameOfLotInfo = value; } }
        public string NodeNameOfTransferState { get { return nodeNameOfTransferState; } set { nodeNameOfTransferState = value; } }
        public string NodeNameOfCommandInfo { get { return nodeNameOfCommandInfo; } set { nodeNameOfCommandInfo = value; } }
        public string NodeNameOfTransferInfos { get { return nodeNameOfTransferInfos; } set { nodeNameOfTransferInfos = value; } }
        public string NodeNameOfTransferInfo { get { return nodeNameOfTransferInfo; } set { nodeNameOfTransferInfo = value; } }
        public string NodeNameOfSourcePort { get { return nodeNameOfSourcePort; } set { nodeNameOfSourcePort = value; } }
        public string NodeNameOfDestPort { get { return nodeNameOfDestPort; } set { nodeNameOfDestPort = value; } }
        public string XpathNameOfPortId { get { return xpathNameOfPortId; } set { xpathNameOfPortId = value; } }
        public string XpathNameOfPortTransferState { get { return xpathNameOfPortTransferState; } set { xpathNameOfPortTransferState = value; } }
        public string XpathNameOfInOutType { get { return xpathNameOfInOutType; } set { xpathNameOfInOutType = value; } }
        public string XpathNameOfPortInOutType { get { return xpathNameOfPortInOutType; } set { xpathNameOfPortInOutType = value; } }
        public string XpathNameOfAccessMode { get { return xpathNameOfAccessMode; } set { xpathNameOfAccessMode = value; } }
        public string XpathNameOfSubState { get { return xpathNameOfSubState; } set { xpathNameOfSubState = value; } }
        public string XpathNameOfLotInfo { get { return xpathNameOfLotInfo; } set { xpathNameOfLotInfo = value; } }
        public string NodeNameOfTransferPort { get { return nodeNameOfTransferPort; } set { nodeNameOfTransferPort = value; } }
        public string NodeNameOfVehicleStatus { get { return nodeNameOfVehicleStatus; } set { nodeNameOfVehicleStatus = value; } }
        public string XpathNameOfTransferPort { get { return xpathNameOfTransferPort; } set { xpathNameOfTransferPort = value; } }
        public string XpathNameOfVehicleStatus { get { return xpathNameOfVehicleStatus; } set { xpathNameOfVehicleStatus = value; } }
        public string NodeNameOfZoneName { get { return nodeNameOfZoneName; } set { nodeNameOfZoneName = value; } }
        public string NodeNameOfZoneCapacity { get { return nodeNameOfZoneCapacity; } set { nodeNameOfZoneCapacity = value; } }
        public string XpathNameOfZoneName { get { return xpathNameOfZoneName; } set { xpathNameOfZoneName = value; } }
        public string XpathNameOfZoneCapacity { get { return xpathNameOfZoneCapacity; } set { xpathNameOfZoneCapacity = value; } }
        public string NodeNameOfErrorId { get { return nodeNameOfErrorId; } set { nodeNameOfErrorId = value; } }
        public string NodeNameOfErrorNumber { get { return nodeNameOfErrorNumber; } set { nodeNameOfErrorNumber = value; } }
        public string NodeNameOfUnitState { get { return nodeNameOfUnitState; } set { nodeNameOfUnitState = value; } }
        public string NodeNameOfRecoveryOptions { get { return nodeNameOfRecoveryOptions; } set { nodeNameOfRecoveryOptions = value; } }
        public string XpathNameOfErrorId { get { return xpathNameOfErrorId; } set { xpathNameOfErrorId = value; } }
        public string XpathNameOfErrorNumber { get { return xpathNameOfErrorNumber; } set { xpathNameOfErrorNumber = value; } }
        public string XpathNameOfUnitState { get { return xpathNameOfUnitState; } set { xpathNameOfUnitState = value; } }
        public string XpathNameOfRecoveryOptions { get { return xpathNameOfRecoveryOptions; } set { xpathNameOfRecoveryOptions = value; } }
        public string NodeNameOfAlarmCode { get { return nodeNameOfAlarmCode; } set { nodeNameOfAlarmCode = value; } }
        public string NodeNameOfAlarmId { get { return nodeNameOfAlarmId; } set { nodeNameOfAlarmId = value; } }
        public string NodeNameOfAlarmText { get { return nodeNameOfAlarmText; } set { nodeNameOfAlarmText = value; } }
        public string XpathNameOfAlarmCode { get { return xpathNameOfAlarmCode; } set { xpathNameOfAlarmCode = value; } }
        public string XpathNameOfAlarmId { get { return xpathNameOfAlarmId; } set { xpathNameOfAlarmId = value; } }
        public string XpathNameOfAlarmText { get { return xpathNameOfAlarmText; } set { xpathNameOfAlarmText = value; } }
        public string NodeNameOfCurrentUnitPosition { get { return nodeNameOfCurrentUnitPosition; } set { nodeNameOfCurrentUnitPosition = value; } }
        public string NodeNameOfUnitStateClearable { get { return nodeNameOfUnitStateClearable; } set { nodeNameOfUnitStateClearable = value; } }
        public string XpathNameOfCurrentUnitPosition { get { return xpathNameOfCurrentUnitPosition; } set { xpathNameOfCurrentUnitPosition = value; } }
        public string XpathNameOfUnitStateClearable { get { return xpathNameOfUnitStateClearable; } set { xpathNameOfUnitStateClearable = value; } }
        public string NodeNameOfIdReadState { get { return nodeNameOfIdReadState; } set { nodeNameOfIdReadState = value; } }
        public string XpathNameOfIdReadState { get { return xpathNameOfIdReadState; } set { xpathNameOfIdReadState = value; } }
        public string NodeNameOfTerminalId { get { return nodeNameOfTerminalId; } set { nodeNameOfTerminalId = value; } }
        public string NodeNameOfInformation { get { return nodeNameOfInformation; } set { nodeNameOfInformation = value; } }
        public string XpathNameOfTerminalId { get { return xpathNameOfTerminalId; } set { xpathNameOfTerminalId = value; } }
        public string XpathNameOfInformation { get { return xpathNameOfInformation; } set { xpathNameOfInformation = value; } }
        public string NodeNameOfCommandType { get { return nodeNameOfCommandType; } set { nodeNameOfCommandType = value; } }
        public string XpathNameOfCommandType { get { return xpathNameOfCommandType; } set { xpathNameOfCommandType = value; } }
        public string NodeNameOfPnpId { get { return nodeNameOfPnpId; } set { nodeNameOfPnpId = value; } }
        public string XpathNameOfPnpId { get { return xpathNameOfPnpId; } set { xpathNameOfPnpId = value; } }
        public string NodeNameOfShuttleId { get { return nodeNameOfShuttleId; } set { nodeNameOfShuttleId = value; } }
        public string NodeNameOfLocation { get { return nodeNameOfLocation; } set { nodeNameOfLocation = value; } }
        public string XpathNameOfShuttleId { get { return xpathNameOfShuttleId; } set { xpathNameOfShuttleId = value; } }
        public string XpathNameOfLocation { get { return xpathNameOfLocation; } set { xpathNameOfLocation = value; } }
        public string NodeNameOfTscState { get { return nodeNameOfTscState; } set { nodeNameOfTscState = value; } }
        public string XpathNameOfTscState { get { return xpathNameOfTscState; } set { xpathNameOfTscState = value; } }
        public string NodeNameOfControlState { get { return nodeNameOfControlState; } set { nodeNameOfControlState = value; } }
        public string XpathNameOfControlState { get { return xpathNameOfControlState; } set { xpathNameOfControlState = value; } }
        public string NodeNameOfEnhancedActiveZones { get { return nodeNameOfEnhancedActiveZones; } set { nodeNameOfEnhancedActiveZones = value; } }
        public string NodeNameOfEnhancedActiveZonesZoneName { get { return nodeNameOfEnhancedActiveZonesZoneName; } set { nodeNameOfEnhancedActiveZonesZoneName = value; } }
        public string NodeNameOfEnhancedActiveZonesZoneCapacity { get { return nodeNameOfEnhancedActiveZonesZoneCapacity; } set { nodeNameOfEnhancedActiveZonesZoneCapacity = value; } }
        public string NodeNameOfEnhancedActiveZonesZoneSize { get { return nodeNameOfEnhancedActiveZonesZoneSize; } set { nodeNameOfEnhancedActiveZonesZoneSize = value; } }
        public string NodeNameOfEnhancedActiveZonesZoneType { get { return nodeNameOfEnhancedActiveZonesZoneType; } set { nodeNameOfEnhancedActiveZonesZoneType = value; } }
        public string XpathNameOfEnhancedActiveZones { get { return xpathNameOfEnhancedActiveZones; } set { xpathNameOfEnhancedActiveZones = value; } }
        public string XpathNameOfEnhancedActiveZonesZoneName { get { return xpathNameOfEnhancedActiveZonesZoneName; } set { xpathNameOfEnhancedActiveZonesZoneName = value; } }
        public string XpathNameOfEnhancedActiveZonesZoneCapacity { get { return xpathNameOfEnhancedActiveZonesZoneCapacity; } set { xpathNameOfEnhancedActiveZonesZoneCapacity = value; } }
        public string XpathNameOfEnhancedActiveZonesZoneSize { get { return xpathNameOfEnhancedActiveZonesZoneSize; } set { xpathNameOfEnhancedActiveZonesZoneSize = value; } }
        public string XpathNameOfEnhancedActiveZonesZoneType { get { return xpathNameOfEnhancedActiveZonesZoneType; } set { xpathNameOfEnhancedActiveZonesZoneType = value; } }
        public string NodeNameOfEnhancedAlarmsAlarmSet { get { return nodeNameOfEnhancedAlarmsAlarmSet; } set { nodeNameOfEnhancedAlarmsAlarmSet = value; } }
        public string NodeNameOfEnhancedAlarmsAlarmId { get { return nodeNameOfEnhancedAlarmsAlarmId; } set { nodeNameOfEnhancedAlarmsAlarmId = value; } }
        public string NodeNameOfEnhancedAlarmsAlarmCode { get { return nodeNameOfEnhancedAlarmsAlarmCode; } set { nodeNameOfEnhancedAlarmsAlarmCode = value; } }
        public string NodeNameOfEnhancedAlarmsAlarmText { get { return nodeNameOfEnhancedAlarmsAlarmText; } set { nodeNameOfEnhancedAlarmsAlarmText = value; } }
        public string XpathNameOfEnhancedAlarmsAlarmSet { get { return xpathNameOfEnhancedAlarmsAlarmSet; } set { xpathNameOfEnhancedAlarmsAlarmSet = value; } }
        public string XpathNameOfEnhancedAlarmsAlarmId { get { return xpathNameOfEnhancedAlarmsAlarmId; } set { xpathNameOfEnhancedAlarmsAlarmId = value; } }
        public string XpathNameOfEnhancedAlarmsAlarmCode { get { return xpathNameOfEnhancedAlarmsAlarmCode; } set { xpathNameOfEnhancedAlarmsAlarmCode = value; } }
        public string XpathNameOfEnhancedAlarmsAlarmText { get { return xpathNameOfEnhancedAlarmsAlarmText; } set { xpathNameOfEnhancedAlarmsAlarmText = value; } }
        public string NodeNameOfEnhancedUnitAlarms { get { return nodeNameOfEnhancedUnitAlarms; } set { nodeNameOfEnhancedUnitAlarms = value; } }
        public string NodeNameOfEnhancedUnitAlarmsUnitId { get { return nodeNameOfEnhancedUnitAlarmsUnitId; } set { nodeNameOfEnhancedUnitAlarmsUnitId = value; } }
        public string NodeNameOfEnhancedUnitAlarmsAlarmId { get { return nodeNameOfEnhancedUnitAlarmsAlarmId; } set { nodeNameOfEnhancedUnitAlarmsAlarmId = value; } }
        public string NodeNameOfEnhancedUnitAlarmsAlarmCode { get { return nodeNameOfEnhancedUnitAlarmsAlarmCode; } set { nodeNameOfEnhancedUnitAlarmsAlarmCode = value; } }
        public string NodeNameOfEnhancedUnitAlarmsAlarmText { get { return nodeNameOfEnhancedUnitAlarmsAlarmText; } set { nodeNameOfEnhancedUnitAlarmsAlarmText = value; } }
        public string NodeNameOfEnhancedUnitAlarmsCurrentUnitPosition { get { return nodeNameOfEnhancedUnitAlarmsCurrentUnitPosition; } set { nodeNameOfEnhancedUnitAlarmsCurrentUnitPosition = value; } }
        public string NodeNameOfEnhancedUnitAlarmsUnitStateClearable { get { return nodeNameOfEnhancedUnitAlarmsUnitStateClearable; } set { nodeNameOfEnhancedUnitAlarmsUnitStateClearable = value; } }
        public string XpathNameOfEnhancedUnitAlarms { get { return xpathNameOfEnhancedUnitAlarms; } set { xpathNameOfEnhancedUnitAlarms = value; } }
        public string XpathNameOfEnhancedUnitAlarmsUnitId { get { return xpathNameOfEnhancedUnitAlarmsUnitId; } set { xpathNameOfEnhancedUnitAlarmsUnitId = value; } }
        public string XpathNameOfEnhancedUnitAlarmsAlarmId { get { return xpathNameOfEnhancedUnitAlarmsAlarmId; } set { xpathNameOfEnhancedUnitAlarmsAlarmId = value; } }
        public string XpathNameOfEnhancedUnitAlarmsAlarmCode { get { return xpathNameOfEnhancedUnitAlarmsAlarmCode; } set { xpathNameOfEnhancedUnitAlarmsAlarmCode = value; } }
        public string XpathNameOfEnhancedUnitAlarmsAlarmText { get { return xpathNameOfEnhancedUnitAlarmsAlarmText; } set { xpathNameOfEnhancedUnitAlarmsAlarmText = value; } }
        public string XpathNameOfEnhancedUnitAlarmsCurrentUnitPosition { get { return xpathNameOfEnhancedUnitAlarmsCurrentUnitPosition; } set { xpathNameOfEnhancedUnitAlarmsCurrentUnitPosition = value; } }
        public string XpathNameOfEnhancedUnitAlarmsUnitStateClearable { get { return xpathNameOfEnhancedUnitAlarmsUnitStateClearable; } set { xpathNameOfEnhancedUnitAlarmsUnitStateClearable = value; } }
        public string NodeNameOfEnhancedCarriers { get { return nodeNameOfEnhancedCarriers; } set { nodeNameOfEnhancedCarriers = value; } }
        public string NodeNameOfEnhancedCarriersCarrierId { get { return nodeNameOfEnhancedCarriersCarrierId; } set { nodeNameOfEnhancedCarriersCarrierId = value; } }
        public string NodeNameOfEnhancedCarriersVehicleId { get { return nodeNameOfEnhancedCarriersVehicleId; } set { nodeNameOfEnhancedCarriersVehicleId = value; } }
        public string NodeNameOfEnhancedCarriersCarrierLoc { get { return nodeNameOfEnhancedCarriersCarrierLoc; } set { nodeNameOfEnhancedCarriersCarrierLoc = value; } }
        public string NodeNameOfEnhancedCarriersInstallTime { get { return nodeNameOfEnhancedCarriersInstallTime; } set { nodeNameOfEnhancedCarriersInstallTime = value; } }
        public string NodeNameOfEnhancedCarriersCarrierZoneName { get { return nodeNameOfEnhancedCarriersCarrierZoneName; } set { nodeNameOfEnhancedCarriersCarrierZoneName = value; } }
        public string NodeNameOfEnhancedCarriersCarrierState { get { return nodeNameOfEnhancedCarriersCarrierState; } set { nodeNameOfEnhancedCarriersCarrierState = value; } }
        public string NodeNameOfEnhancedCarriersCarrierType { get { return nodeNameOfEnhancedCarriersCarrierType; } set { nodeNameOfEnhancedCarriersCarrierType = value; } }
        public string XpathNameOfEnhancedCarriers { get { return xpathNameOfEnhancedCarriers; } set { xpathNameOfEnhancedCarriers = value; } }
        public string XpathNameOfEnhancedCarriersCarrierId { get { return xpathNameOfEnhancedCarriersCarrierId; } set { xpathNameOfEnhancedCarriersCarrierId = value; } }
        public string XpathNameOfEnhancedCarriersVehicleId { get { return xpathNameOfEnhancedCarriersVehicleId; } set { xpathNameOfEnhancedCarriersVehicleId = value; } }
        public string XpathNameOfEnhancedCarriersCarrierLoc { get { return xpathNameOfEnhancedCarriersCarrierLoc; } set { xpathNameOfEnhancedCarriersCarrierLoc = value; } }
        public string XpathNameOfEnhancedCarriersInstallTime { get { return xpathNameOfEnhancedCarriersInstallTime; } set { xpathNameOfEnhancedCarriersInstallTime = value; } }
        public string XpathNameOfEnhancedCarriersCarrierZoneName { get { return xpathNameOfEnhancedCarriersCarrierZoneName; } set { xpathNameOfEnhancedCarriersCarrierZoneName = value; } }
        public string XpathNameOfEnhancedCarriersCarrierState { get { return xpathNameOfEnhancedCarriersCarrierState; } set { xpathNameOfEnhancedCarriersCarrierState = value; } }
        public string XpathNameOfEnhancedCarriersCarrierType { get { return xpathNameOfEnhancedCarriersCarrierType; } set { xpathNameOfEnhancedCarriersCarrierType = value; } }
        public string NodeNameOfEnhancedTransfers { get { return nodeNameOfEnhancedTransfers; } set { nodeNameOfEnhancedTransfers = value; } }
        public string NodeNameOfEnhancedTransfersCommandInfo { get { return nodeNameOfEnhancedTransfersCommandInfo; } set { nodeNameOfEnhancedTransfersCommandInfo = value; } }
        public string NodeNameOfEnhancedTransfersTransferInfo { get { return nodeNameOfEnhancedTransfersTransferInfo; } set { nodeNameOfEnhancedTransfersTransferInfo = value; } }
        public string NodeNameOfEnhancedTransfersTransferState { get { return nodeNameOfEnhancedTransfersTransferState; } set { nodeNameOfEnhancedTransfersTransferState = value; } }
        public string NodeNameOfEnhancedTransfersCommandId { get { return nodeNameOfEnhancedTransfersCommandId; } set { nodeNameOfEnhancedTransfersCommandId = value; } }
        public string NodeNameOfEnhancedTransfersPriority { get { return nodeNameOfEnhancedTransfersPriority; } set { nodeNameOfEnhancedTransfersPriority = value; } }
        public string NodeNameOfEnhancedTransfersReplace { get { return nodeNameOfEnhancedTransfersReplace; } set { nodeNameOfEnhancedTransfersReplace = value; } }
        public string NodeNameOfEnhancedTransfersCarrierId { get { return nodeNameOfEnhancedTransfersCarrierId; } set { nodeNameOfEnhancedTransfersCarrierId = value; } }
        public string NodeNameOfEnhancedTransfersCarrierLoc { get { return nodeNameOfEnhancedTransfersCarrierLoc; } set { nodeNameOfEnhancedTransfersCarrierLoc = value; } }
        public string NodeNameOfEnhancedTransfersSource { get { return nodeNameOfEnhancedTransfersSource; } set { nodeNameOfEnhancedTransfersSource = value; } }
        public string NodeNameOfEnhancedTransfersDest { get { return nodeNameOfEnhancedTransfersDest; } set { nodeNameOfEnhancedTransfersDest = value; } }
        public string NodeNameOfEnhancedTransfersSourcePort { get { return nodeNameOfEnhancedTransfersSourcePort; } set { nodeNameOfEnhancedTransfersSourcePort = value; } }
        public string NodeNameOfEnhancedTransfersDestPort { get { return nodeNameOfEnhancedTransfersDestPort; } set { nodeNameOfEnhancedTransfersDestPort = value; } }
        public string XpathNameOfEnhancedTransfers { get { return xpathNameOfEnhancedTransfers; } set { xpathNameOfEnhancedTransfers = value; } }
        public string XpathNameOfEnhancedTransfersTransferState { get { return xpathNameOfEnhancedTransfersTransferState; } set { xpathNameOfEnhancedTransfersTransferState = value; } }
        public string XpathNameOfEnhancedTransfersCommandId { get { return xpathNameOfEnhancedTransfersCommandId; } set { xpathNameOfEnhancedTransfersCommandId = value; } }
        public string XpathNameOfEnhancedTransfersPriority { get { return xpathNameOfEnhancedTransfersPriority; } set { xpathNameOfEnhancedTransfersPriority = value; } }
        public string XpathNameOfEnhancedTransfersReplace { get { return xpathNameOfEnhancedTransfersReplace; } set { xpathNameOfEnhancedTransfersReplace = value; } }
        public string XpathNameOfEnhancedTransfersCarrierId { get { return xpathNameOfEnhancedTransfersCarrierId; } set { xpathNameOfEnhancedTransfersCarrierId = value; } }
        public string XpathNameOfEnhancedTransfersSource { get { return xpathNameOfEnhancedTransfersSource; } set { xpathNameOfEnhancedTransfersSource = value; } }
        public string XpathNameOfEnhancedTransfersDest { get { return xpathNameOfEnhancedTransfersDest; } set { xpathNameOfEnhancedTransfersDest = value; } }
        public string NodeNameOfEnhancedVehicles { get { return nodeNameOfEnhancedVehicles; } set { nodeNameOfEnhancedVehicles = value; } }
        public string NodeNameOfEnhancedVehiclesVehicleId { get { return nodeNameOfEnhancedVehiclesVehicleId; } set { nodeNameOfEnhancedVehiclesVehicleId = value; } }
        public string NodeNameOfEnhancedVehiclesVehicleState { get { return nodeNameOfEnhancedVehiclesVehicleState; } set { nodeNameOfEnhancedVehiclesVehicleState = value; } }
        public string NodeNameOfEnhancedVehiclesVehicleStatus { get { return nodeNameOfEnhancedVehiclesVehicleStatus; } set { nodeNameOfEnhancedVehiclesVehicleStatus = value; } }
        public string NodeNameOfEnhancedVehiclesVehicleLocation { get { return nodeNameOfEnhancedVehiclesVehicleLocation; } set { nodeNameOfEnhancedVehiclesVehicleLocation = value; } }
        public string XpathNameOfEnhancedVehicles { get { return xpathNameOfEnhancedVehicles; } set { xpathNameOfEnhancedVehicles = value; } }
        public string XpathNameOfEnhancedVehiclesVehicleId { get { return xpathNameOfEnhancedVehiclesVehicleId; } set { xpathNameOfEnhancedVehiclesVehicleId = value; } }
        public string XpathNameOfEnhancedVehiclesVehicleState { get { return xpathNameOfEnhancedVehiclesVehicleState; } set { xpathNameOfEnhancedVehiclesVehicleState = value; } }
        public string XpathNameOfEnhancedVehiclesVehicleStatus { get { return xpathNameOfEnhancedVehiclesVehicleStatus; } set { xpathNameOfEnhancedVehiclesVehicleStatus = value; } }
        public string XpathNameOfEnhancedVehiclesVehicleLocation { get { return xpathNameOfEnhancedVehiclesVehicleLocation; } set { xpathNameOfEnhancedVehiclesVehicleLocation = value; } }
        public string NodeNameOfEnhancedPorts { get { return nodeNameOfEnhancedPorts; } set { nodeNameOfEnhancedPorts = value; } }
        public string NodeNameOfEnhancedPortsPortId { get { return nodeNameOfEnhancedPortsPortId; } set { nodeNameOfEnhancedPortsPortId = value; } }
        public string NodeNameOfEnhancedPortsState { get { return nodeNameOfEnhancedPortsState; } set { nodeNameOfEnhancedPortsState = value; } }
        public string NodeNameOfEnhancedPortsPortTransferState { get { return nodeNameOfEnhancedPortsPortTransferState; } set { nodeNameOfEnhancedPortsPortTransferState = value; } }
        public string NodeNameOfEnhancedPortsSubState { get { return nodeNameOfEnhancedPortsSubState; } set { nodeNameOfEnhancedPortsSubState = value; } }
        public string NodeNameOfEnhancedPortsPortAccessMode { get { return nodeNameOfEnhancedPortsPortAccessMode; } set { nodeNameOfEnhancedPortsPortAccessMode = value; } }
        public string NodeNameOfEnhancedPortsPortInOutType { get { return nodeNameOfEnhancedPortsPortInOutType; } set { nodeNameOfEnhancedPortsPortInOutType = value; } }
        public string NodeNameOfEnhancedPortsPortProcessingState { get { return nodeNameOfEnhancedPortsPortProcessingState; } set { nodeNameOfEnhancedPortsPortProcessingState = value; } }
        public string NodeNameOfEnhancedportsUseRfReader { get { return nodeNameOfEnhancedportsUseRfReader; } set { nodeNameOfEnhancedportsUseRfReader = value; } }
        public string XpathNameOfEnhancedPorts { get { return xpathNameOfEnhancedPorts; } set { xpathNameOfEnhancedPorts = value; } }
        public string XpathNameOfEnhancedPortsPortId { get { return xpathNameOfEnhancedPortsPortId; } set { xpathNameOfEnhancedPortsPortId = value; } }
        public string XpathNameOfEnhancedPortsState { get { return xpathNameOfEnhancedPortsState; } set { xpathNameOfEnhancedPortsState = value; } }
        public string XpathNameOfEnhancedPortsPortTransferState { get { return xpathNameOfEnhancedPortsPortTransferState; } set { xpathNameOfEnhancedPortsPortTransferState = value; } }
        public string XpathNameOfEnhancedPortsSubState { get { return xpathNameOfEnhancedPortsSubState; } set { xpathNameOfEnhancedPortsSubState = value; } }
        public string XpathNameOfEnhancedPortsPortAccessMode { get { return xpathNameOfEnhancedPortsPortAccessMode; } set { xpathNameOfEnhancedPortsPortAccessMode = value; } }
        public string XpathNameOfEnhancedPortsPortInOutType { get { return xpathNameOfEnhancedPortsPortInOutType; } set { xpathNameOfEnhancedPortsPortInOutType = value; } }
        public string XpathNameOfEnhancedPortsPortProcessingState { get { return xpathNameOfEnhancedPortsPortProcessingState; } set { xpathNameOfEnhancedPortsPortProcessingState = value; } }
        public string XpathNameOfEnhancedPortsUseRfReader { get { return xpathNameOfEnhancedPortsUseRfReader; } set { xpathNameOfEnhancedPortsUseRfReader = value; } }
        public string NodeNameOfEnhancedShelves { get { return nodeNameOfEnhancedShelves; } set { nodeNameOfEnhancedShelves = value; } }
        public string NodeNameOfEnhancedShelvesShelfName { get { return nodeNameOfEnhancedShelvesShelfName; } set { nodeNameOfEnhancedShelvesShelfName = value; } }
        public string NodeNameOfEnhancedShelvesShelfState { get { return nodeNameOfEnhancedShelvesShelfState; } set { nodeNameOfEnhancedShelvesShelfState = value; } }
        public string NodeNameOfEnhancedShelvesShelfStatus { get { return nodeNameOfEnhancedShelvesShelfStatus; } set { nodeNameOfEnhancedShelvesShelfStatus = value; } }
        public string XpathNameOfEnhancedShelves { get { return xpathNameOfEnhancedShelves; } set { xpathNameOfEnhancedShelves = value; } }
        public string XpathNameOfEnhancedShelvesShelfName { get { return xpathNameOfEnhancedShelvesShelfName; } set { xpathNameOfEnhancedShelvesShelfName = value; } }
        public string XpathNameOfEnhancedShelvesShelfState { get { return xpathNameOfEnhancedShelvesShelfState; } set { xpathNameOfEnhancedShelvesShelfState = value; } }
        public string XpathNameOfEnhancedShelvesShelfStatus { get { return xpathNameOfEnhancedShelvesShelfStatus; } set { xpathNameOfEnhancedShelvesShelfStatus = value; } }
        public string NodeNameOfEnhancedShuttles { get { return nodeNameOfEnhancedShuttles; } set { nodeNameOfEnhancedShuttles = value; } }
        public string NodeNameOfEnhancedShuttlesLifterName { get { return nodeNameOfEnhancedShuttlesLifterName; } set { nodeNameOfEnhancedShuttlesLifterName = value; } }
        public string NodeNameOfEnhancedShuttlesShuttleName { get { return nodeNameOfEnhancedShuttlesShuttleName; } set { nodeNameOfEnhancedShuttlesShuttleName = value; } }
        public string NodeNameOfEnhancedShuttlesLocation { get { return nodeNameOfEnhancedShuttlesLocation; } set { nodeNameOfEnhancedShuttlesLocation = value; } }
        public string NodeNameOfEnhancedShuttlesShuttleState { get { return nodeNameOfEnhancedShuttlesShuttleState; } set { nodeNameOfEnhancedShuttlesShuttleState = value; } }
        public string XpathNameOfEnhancedShuttles { get { return xpathNameOfEnhancedShuttles; } set { xpathNameOfEnhancedShuttles = value; } }
        public string XpathNameOfEnhancedShuttlesLifterName { get { return xpathNameOfEnhancedShuttlesLifterName; } set { xpathNameOfEnhancedShuttlesLifterName = value; } }
        public string XpathNameOfEnhancedShuttlesShuttleName { get { return xpathNameOfEnhancedShuttlesShuttleName; } set { xpathNameOfEnhancedShuttlesShuttleName = value; } }
        public string XpathNameOfEnhancedShuttlesLocation { get { return xpathNameOfEnhancedShuttlesLocation; } set { xpathNameOfEnhancedShuttlesLocation = value; } }
        public string XpathNameOfEnhancedShuttlesShuttleState { get { return xpathNameOfEnhancedShuttlesShuttleState; } set { xpathNameOfEnhancedShuttlesShuttleState = value; } }
        public string NodeNameOfCurrentPortTransferStates { get { return nodeNameOfCurrentPortTransferStates; } set { nodeNameOfCurrentPortTransferStates = value; } }
        public string NodeNameOfCurrentPortTransferStatesPortInfo { get { return nodeNameOfCurrentPortTransferStatesPortInfo; } set { nodeNameOfCurrentPortTransferStatesPortInfo = value; } }
        public string NodeNameOfCurrentPortTransferStatesPortInfoPortId { get { return nodeNameOfCurrentPortTransferStatesPortInfoPortId; } set { nodeNameOfCurrentPortTransferStatesPortInfoPortId = value; } }
        public string NodeNameOfCurrentPortTransferStatesPortInfoPortTransferState { get { return nodeNameOfCurrentPortTransferStatesPortInfoPortTransferState; } set { nodeNameOfCurrentPortTransferStatesPortInfoPortTransferState = value; } }
        public string XpathNameOfCurrentPortTransferStates { get { return xpathNameOfCurrentPortTransferStates; } set { xpathNameOfCurrentPortTransferStates = value; } }
        public string XpathNameOfCurrentPortTransferStatesPortInfo { get { return xpathNameOfCurrentPortTransferStatesPortInfo; } set { xpathNameOfCurrentPortTransferStatesPortInfo = value; } }
        public string XpathNameOfCurrentPortTransferStatesPortInfoPortId { get { return xpathNameOfCurrentPortTransferStatesPortInfoPortId; } set { xpathNameOfCurrentPortTransferStatesPortInfoPortId = value; } }
        public string XpathNameOfCurrentPortTransferStatesPortInfoPortTransferState { get { return xpathNameOfCurrentPortTransferStatesPortInfoPortTransferState; } set { xpathNameOfCurrentPortTransferStatesPortInfoPortTransferState = value; } }
        public string NodeNameOfEnhancedControlState { get { return nodeNameOfEnhancedControlState; } set { nodeNameOfEnhancedControlState = value; } }
        public string XpathNameOfEnhancedControlState { get { return xpathNameOfEnhancedControlState; } set { xpathNameOfEnhancedControlState = value; } }
        public string NodeNameOfEnhancedCraneStates { get { return nodeNameOfEnhancedCraneStates; } set { nodeNameOfEnhancedCraneStates = value; } }
        public string NodeNameOfEnhancedCraneStatesStockerCraneId { get { return nodeNameOfEnhancedCraneStatesStockerCraneId; } set { nodeNameOfEnhancedCraneStatesStockerCraneId = value; } }
        public string NodeNameOfEnhancedCraneStatesCraneState { get { return nodeNameOfEnhancedCraneStatesCraneState; } set { nodeNameOfEnhancedCraneStatesCraneState = value; } }
        public string XpathNameOfEnhancedCraneStates { get { return xpathNameOfEnhancedCraneStates; } set { xpathNameOfEnhancedCraneStates = value; } }
        public string XpathNameOfEnhancedCraneStatesStockerCraneId { get { return xpathNameOfEnhancedCraneStatesStockerCraneId; } set { xpathNameOfEnhancedCraneStatesStockerCraneId = value; } }
        public string XpathNameOfEnhancedCraneStatesCraneState { get { return xpathNameOfEnhancedCraneStatesCraneState; } set { xpathNameOfEnhancedCraneStatesCraneState = value; } }
        public string NodeNameOfEnhancedStockerStatus { get { return nodeNameOfEnhancedStockerStatus; } set { nodeNameOfEnhancedStockerStatus = value; } }
        public string NodeNameOfEnhancedStockerStatusMachineName { get { return nodeNameOfEnhancedStockerStatusMachineName; } set { nodeNameOfEnhancedStockerStatusMachineName = value; } }
        public string NodeNameOfEnhancedStockerStatusStockerState { get { return nodeNameOfEnhancedStockerStatusStockerState; } set { nodeNameOfEnhancedStockerStatusStockerState = value; } }
        public string XpathNameOfEnhancedStockerStatus { get { return xpathNameOfEnhancedStockerStatus; } set { xpathNameOfEnhancedStockerStatus = value; } }
        public string XpathNameOfEnhancedStockerStatusMachineName { get { return xpathNameOfEnhancedStockerStatusMachineName; } set { xpathNameOfEnhancedStockerStatusMachineName = value; } }
        public string XpathNameOfEnhancedStockerStatusStockerState { get { return xpathNameOfEnhancedStockerStatusStockerState; } set { xpathNameOfEnhancedStockerStatusStockerState = value; } }
    }
}
