using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using ACS.Framework.Resource.Model.Factory.Zone;
using ACS.Framework.Resource.Model.Factory.Machine;
using ACS.Framework.Resource.Model.Factory.Unit;
using ACS.Framework.Resource.Model.Factory.Position;
using ACS.Framework.Resource.Model.Alternate;
using ACS.Framework.Material.Model;
using ACS.Framework.Transfer.Model;
using ACS.Framework.Transfer;
using ACS.Framework.Route.Model;
using ACS.Framework.Route.Model.BidirectionalNode;

namespace ACS.Framework.Message.Model
{
    public class BaseMessage : AbstractMessage
    {

        protected static Logging.Logger logger = Logging.Logger.GetLogger(typeof(BaseMessage));
        public static string UI_MESSAGE_PREFIX = "UI";
        public static string CURRENT_TYPE_PORT = "PORT";
        public static string CURRENT_TYPE_SHELF = "SHELF";
        public static string CURRENT_TYPE_VEHICLE = "VEHICLE";
        public static string CURRENT_TYPE_CRANE = "CRANE";
        public static string CURRENT_TYPE_ZONE = "ZONE";
        public static string COMMANDTYPE_TRANSFER = "TRANSFER";
        public static string COMMANDTYPE_CANCEL = "CANCEL";
        public static string COMMANDTYPE_ABORT = "ABORT";
        public static string MESSAGENAME_MASSSTORAGE_ONLINECONNECTED = "MASSSTORAGE-ONLINECONNECTED";
        public static string MESSAGENAME_MASSSTORAGE_ONLINEDISCONNECTED = "MASSSTORAGE-ONLINEDISCONNECTED";
        public static string MESSAGENAME_MASSSTORAGE_MESSAGERECEIVED = "MASSSTORAGE-MESSAGERECEIVED";
        public static string MESSAGENAME_MASSSTORAGE_CONTROLSTATEREMOTE = "MASSSTORAGE-CONTROLSTATEREMOTE";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERREMOVE = "MASSSTORAGE-CARRIERREMOVE";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERINSTALL = "MASSSTORAGE-CARRIERINSTALL";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERLOCATE = "MASSSTORAGE-CARRIERLOCATE";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERINFOUPDATE = "MASSSTORAGE-CARRIERINFOUPDATE";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERWAITIN = "MASSSTORAGE-CARRIERWAITIN";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERWAITOUT = "MASSSTORAGE-CARRIERWAITOUT";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERSTORED = "MASSSTORAGE-CARRIERSTORED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERSTOREDALT = "MASSSTORAGE-CARRIERSTOREDALT";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERINSTALLCOMPLETED = "MASSSTORAGE-CARRIERINSTALLCOMPLETED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERREMOVECOMPLETED = "MASSSTORAGE-CARRIERREMOVECOMPLETED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERREMOVED = "MASSSTORAGE-CARRIERREMOVED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERRESUMED = "MASSSTORAGE-CARRIERRESUMED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERIDREAD = "MASSSTORAGE-CARRIERIDREAD";
        public static string MESSAGENAME_MASSSTORAGE_PAUSE = "MASSSTORAGE-PAUSE";
        public static string MESSAGENAME_MASSSTORAGE_RESUME = "MASSSTORAGE-RESUME";
        public static string MESSAGENAME_MASSSTORAGE_OFFLINE = "MASSSTORAGE-OFFLINE";
        public static string MESSAGENAME_MASSSTORAGE_ONLINELOCAL = "MASSSTORAGE-ONLINELOCAL";
        public static string MESSAGENAME_MASSSTORAGE_ONLINEREMOTE = "MASSSTORAGE-ONLINEREMOTE";
        public static string MESSAGENAME_MASSSTORAGE_DATETIMESET = "MASSSTORAGE-DATETIMESET";
        public static string MESSAGENAME_MASSSTORAGE_PORTINOUTTYPECHANGE = "MASSSTORAGE-PORTINOUTTYPECHANGE";
        public static string MESSAGENAME_MASSSTORAGE_PORTOCCUPIEDCHANGE = "MASSSTORAGE-PORTOCCUPIEDCHANGE";
        public static string MESSAGENAME_MASSSTORAGE_PORTINSERVICE = "MASSSTORAGE-PORTINSERVICE";
        public static string MESSAGENAME_MASSSTORAGE_PORTOUTOFSERVICE = "MASSSTORAGE-PORTOUTOFSERVICE";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERTRANSFER = "MASSSTORAGE-CARRIERTRANSFER";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERTRANSFERRING = "MASSSTORAGE-CARRIERTRANSFERRING";
        public static string MESSAGENAME_MASSSTORAGE_INVENTORYREQUEST = "MASSSTORAGE-INVENTORYREQUEST";
        public static string MESSAGENAME_MASSSTORAGE_STATEREQUEST = "MASSSTORAGE-STATEREQUEST";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERREQUEST = "MASSSTORAGE-TRANSFERREQUEST";
        public static string MESSAGENAME_MASSSTORAGE_INVENTORYIDENTIFICATION = "MASSSTORAGE-INVENTORYIDENTIFICATION";
        public static string MESSAGENAME_MASSSTORAGE_INVENTORYIDENTIFICATIONREPLY = "MASSSTORAGE-INVENTORYIDENTIFICATIONREPLY";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERIDENTIFICATION = "MASSSTORAGE-TRANSFERIDENTIFICATION";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERIDENTIFICATIONREPLY = "MASSSTORAGE-TRANSFERIDENTIFICATIONREPLY";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERINITIATED = "MASSSTORAGE-TRANSFERINITIATED";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERCOMPLETED = "MASSSTORAGE-TRANSFERCOMPLETED";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERABORTINITIATED = "MASSSTORAGE-TRANSFERABORTINITIATED";
        public static string MESSAGENAME_MASSSTORAGE_CARRIERTRANSFERABORTREPLY = "MASSSTORAGE-CARRIERTRANSFERABORTREPLY";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERABORTCOMPLETED = "MASSSTORAGE-TRANSFERABORTCOMPLETED";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERABORTFAILED = "MASSSTORAGE-TRANSFERABORTFAILED";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERCANCELCOMPLETED = "MASSSTORAGE-TRANSFERCANCELCOMPLETED";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERCANCELREPLY = "MASSSTORAGE-TRANSFERCANCELREPLY";
        public static string MESSAGENAME_MASSSTORAGE_TRANSFERCANCELFAILED = "MASSSTORAGE-TRANSFERCANCELFAILED";
        public static string MESSAGENAME_MASSSTORAGE_ABORT = "MASSSTORAGE-ABORT";
        public static string MESSAGENAME_MASSSTORAGE_CANCEL = "MASSSTORAGE-CANCEL";
        public static string MESSAGENAME_MASSSTORAGE_RETRY = "MASSSTORAGE-RETRY";
        public static string MESSAGENAME_MASSSTORAGE_INFORM = "MASSSTORAGE-INFORM";
        public static string MESSAGENAME_MASSSTORAGE_UPDATECOMMAND = "MASSSTORAGE-UPDATECOMMAND";
        public static string MESSAGENAME_MASSSTORAGE_FULL_SET = "MASSSTORAGE-FULL-SET";
        public static string MESSAGENAME_MASSSTORAGE_FULL_RELEASE = "MASSSTORAGE-FULL-RELEASE";
        public static string MESSAGENAME_MASSSTORAGE_SCAN = "MASSSTORAGE-SCAN";
        public static string MESSAGENAME_MASSSTORAGE_PORTIDREADSTATECHANGED = "MASSSTORAGE-PORTIDREADSTATECHANGED";
        public static string MESSAGENAME_MASSSTORAGE_PORTIDREADFAILED = "MASSSTORAGE-PORTIDREADFAILED";
        public static string MESSAGENAME_MASSSTORAGE_PORTIDREADMISMATCHED = "MASSSTORAGE-PORTIDREADMISMATCHED";
        public static string MESSAGENAME_MASSSTORAGE_ABORTREPLY = "MASSSTORAGE-CARRIERTRANSFERABORTREPLY";
        public static string MESSAGENAME_MASSSTORAGE_CANCELREPLY = "MASSSTORAGE-CARRIERTRANSFERCANCELREPLY";
        public static string MESSAGENAME_MASSSTORAGE_CRANEACTIVE = "MASSSTORAGE-CRANEACTIVE";
        public static string MESSAGENAME_MASSSTORAGE_CRANEIDLE = "MASSSTORAGE-CRANEIDLE";
        public static string MESSAGENAME_INTERRAIL_ONLINECONNECTED = "INTERRAIL-ONLINECONNECTED";
        public static string MESSAGENAME_INTERRAIL_ONLINEDISCONNECTED = "INTERRAIL-ONLINEDISCONNECTED";
        public static string MESSAGENAME_INTERRAIL_MESSAGERECEIVED = "INTERRAIL-MESSAGERECEIVED";
        public static string MESSAGENAME_INTERRAIL_CARRIERWAITIN = "INTERRAIL-CARRIERWAITIN";
        public static string MESSAGENAME_INTERRAIL_CARRIERWAITOUT = "INTERRAIL-CARRIERWAITOUT";
        public static string MESSAGENAME_INTERRAIL_CARRIERTRANSFER = "INTERRAIL-CARRIERTRANSFER";
        public static string MESSAGENAME_INTERRAIL_CARRIERTRANSFERRING = "INTERRAIL-CARRIERTRANSFERRING";
        public static string MESSAGENAME_INTERRAIL_CARRIERINSTALL = "INTERRAIL-CARRIERINSTALL";
        public static string MESSAGENAME_INTERRAIL_CARRIERSTORED = "INTERRAIL-CARRIERREMOVED";
        public static string MESSAGENAME_INTERRAIL_ABORT = "INTERRAIL-ABORT";
        public static string MESSAGENAME_INTERRAIL_CANCEL = "INTERRAIL-CANCEL";
        public static string MESSAGENAME_INTERRAIL_RETRY = "INTERRAIL-RETRY";
        public static string MESSAGENAME_INTERRAIL_INFORM = "INTERRAIL-INFORM";
        public static string MESSAGENAME_INTERRAIL_PAUSE = "INTERRAIL-PAUSE";
        public static string MESSAGENAME_INTERRAIL_RESUME = "INTERRAIL-RESUME";
        public static string MESSAGENAME_INTERRAIL_OFFLINE = "INTERRAIL-OFFLINE";
        public static string MESSAGENAME_INTERRAIL_ONLINELOCAL = "INTERRAIL-ONLINELOCAL";
        public static string MESSAGENAME_INTERRAIL_ONLINEREMOTE = "INTERRAIL-ONLINEREMOTE";
        public static string MESSAGENAME_INTERRAIL_DATETIMESET = "INTERRAIL-DATETIMESET";
        public static string MESSAGENAME_INTERRAIL_PORTINOUTTYPECHANGE = "INTERRAIL-PORTINOUTTYPECHANGE";
        public static string MESSAGENAME_INTERRAIL_PORTOCCUPIEDCHANGE = "INTERRAIL-PORTOCCUPIEDCHANGE";
        public static string MESSAGENAME_INTERRAIL_TRANSFERINITIATED = "INTERRAIL-TRANSFERINITIATED";
        public static string MESSAGENAME_INTERRAIL_TRANSFERCOMPLETED = "INTERRAIL-TRANSFERCOMPLETED";
        public static string MESSAGENAME_INTERRAIL_PORTINSERVICE = "INTERRAIL-PORTINSERVICE";
        public static string MESSAGENAME_INTERRAIL_PORTOUTOFSERVICE = "INTERRAIL-PORTOUTOFSERVICE";
        public static string MESSAGENAME_INTERSTORAGE_ONLINECONNECTED = "INTERSTORAGE-ONLINECONNECTED";
        public static string MESSAGENAME_INTERSTORAGE_ONLINEDISCONNECTED = "INTERSTORAGE-ONLINEDISCONNECTED";
        public static string MESSAGENAME_INTERSTORAGE_MESSAGERECEIVED = "INTERSTORAGE-MESSAGERECEIVED";
        public static string MESSAGENAME_INTERSTORAGE_CARRIERTRANSFER = "INTERSTORAGE-CARRIERTRANSFER";
        public static string MESSAGENAME_INTERSTORAGE_ABORT = "INTERSTORAGE-ABORT";
        public static string MESSAGENAME_INTERSTORAGE_CANCEL = "INTERSTORAGE-CANCEL";
        public static string MESSAGENAME_INTERSTORAGE_RETRY = "INTERSTORAGE-RETRY";
        public static string MESSAGENAME_INTERSTORAGE_INFORM = "INTERSTORAGE-INFORM";

        public static string MESSAGENAME_INTERSTORAGE_CARRIERINSTALL = "INTERSTORAGE-CARRIERINSTALL";
        public static string MESSAGENAME_INTERSTORAGE_CARRIERWAITIN = "INTERSTORAGE-CARRIERWAITIN";
        public static string MESSAGENAME_INTERSTORAGE_CARRIERWAITOUT = "INTERSTORAGE-CARRIERWAITOUT";
        public static string MESSAGENAME_INTERSTORAGE_CARRIERTRANSFERRING = "INTERSTORAGE-CARRIERTRANSFERRING";
        public static string MESSAGENAME_INTERSTORAGE_CARRIERREMOVED = "INTERSTORAGE-CARRIERREMOVED";
        public static string MESSAGENAME_INTERSTORAGE_PAUSE = "INTERSTORAGE-PAUSE";
        public static string MESSAGENAME_INTERSTORAGE_RESUME = "INTERSTORAGE-RESUME";
        public static string MESSAGENAME_INTERSTORAGE_OFFLINE = "INTERSTORAGE-OFFLINE";
        public static string MESSAGENAME_INTERSTORAGE_ONLINELOCAL = "INTERSTORAGE-ONLINELOCAL";
        public static string MESSAGENAME_INTERSTORAGE_ONLINEREMOTE = "INTERSTORAGE-ONLINEREMOTE";
        public static string MESSAGENAME_INTERSTORAGE_DATETIMESET = "INTERSTORAGE-DATETIMESET";
        public static string MESSAGENAME_RAIL_ONLINECONNECTED = "RAIL-ONLINECONNECTED";
        public static string MESSAGENAME_RAIL_ONLINEDISCONNECTED = "RAIL-ONLINEDISCONNECTED";
        public static string MESSAGENAME_RAIL_MESSAGERECEIVED = "RAIL-MESSAGERECEIVED";
        public static string MESSAGENAME_RAIL_CARRIERTRANSFER = "RAIL-CARRIERTRANSFER";
        public static string MESSAGENAME_RAIL_CARRIERINSTALL = "RAIL-CARRIERINSTALL";
        public static string MESSAGENAME_RAIL_CARRIERINSTALLED = "RAIL-CARRIERINSTALLED";
        public static string MESSAGENAME_RAIL_CARRIERREMOVED = "RAIL-CARRIERREMOVED";
        public static string MESSAGENAME_RAIL_CARRIERSTORED = "RAIL-CARRIERSTORED";
        public static string MESSAGENAME_RAIL_ABORT = "RAIL-ABORT";
        public static string MESSAGENAME_RAIL_CANCEL = "RAIL-CANCEL";
        public static string MESSAGENAME_RAIL_RETRY = "RAIL-RETRY";
        public static string MESSAGENAME_RAIL_INFORM = "RAIL-INFORM";
        public static string MESSAGENAME_RAIL_STAGECOMMAND = "RAIL-STAGECOMMAND";
        public static string MESSAGENAME_RAIL_STAGEDELETECOMMAND = "RAIL-STAGEDELETECOMMAND";
        public static string MESSAGENAME_RAIL_UPDATECOMMAND = "RAIL-UPDATECOMMAND";
        public static string MESSAGENAME_RAIL_MONITORVEHICLE = "RAIL-MONITORVEHICLE";
        public static string MESSAGENAME_RAIL_PAUSE = "RAIL-PAUSE";
        public static string MESSAGENAME_RAIL_RESUME = "RAIL-RESUME";
        public static string MESSAGENAME_RAIL_OFFLINE = "RAIL-OFFLINE";
        public static string MESSAGENAME_RAIL_ONLINELOCAL = "RAIL-ONLINELOCAL";
        public static string MESSAGENAME_RAIL_ONLINEREMOTE = "RAIL-ONLINEREMOTE";
        public static string MESSAGENAME_RAIL_DATETIMESET = "RAIL-DATETIMESET";
        public static string MESSAGENAME_RAIL_STATEREQUEST = "RAIL-STATEREQUEST";
        public static string MESSAGENAME_RAIL_VEHICLEASSIGNED = "RAIL-VEHICLEASSIGNED";
        public static string MESSAGENAME_RAIL_VEHICLEUNASSIGNED = "RAIL-VEHICLEUNASSIGNED";
        public static string MESSAGENAME_RAIL_VEHICLEARRIVED = "RAIL-VEHICLEARRIVED";
        public static string MESSAGENAME_RAIL_VEHICLEDEPARTED = "RAIL-VEHICLEDEPARTED";
        public static string MESSAGENAME_RAIL_VEHICLEREMOVED = "RAIL-VEHICLEREMOVED";
        public static string MESSAGENAME_RAIL_VEHICLEINSTALLED = "RAIL-VEHICLEINSTALLED";
        public static string MESSAGENAME_RAIL_VEHICLEACQUIRESTARTED = "RAIL-VEHICLEACQUIRESTARTED";
        public static string MESSAGENAME_RAIL_VEHICLEACQUIRECOMPLETED = "RAIL-VEHICLEACQUIRECOMPLETED";
        public static string MESSAGENAME_RAIL_VEHICLEDEPOSITSTARTED = "RAIL-VEHICLEDEPOSITSTARTED";
        public static string MESSAGENAME_RAIL_VEHICLEDEPOSITCOMPLETED = "RAIL-VEHICLEDEPOSITCOMPLETED";
        public static string MESSAGENAME_RAIL_TRANSFERINITIATED = "RAIL-TRANSFERINITIATED";
        public static string MESSAGENAME_RAIL_TRANSFERCOMPLETED = "RAIL-TRANSFERCOMPLETED";
        public static string MESSAGENAME_RAIL_TRANSFERABORTCOMPLETED = "RAIL-TRANSFERABORTCOMPLETED";
        public static string MESSAGENAME_RAIL_CARRIERTRANSFERABORTREPLY = "RAIL-CARRIERTRANSFERABORTREPLY";
        public static string MESSAGENAME_RAIL_TRANSFERABORTFAILED = "RAIL-TRANSFERABORTFAILED";
        public static string MESSAGENAME_RAIL_TRANSFERCANCELCOMPLETED = "RAIL-TRANSFERCANCELCOMPLETED";
        public static string MESSAGENAME_RAIL_CARRIERTRANSFERCANCELREPLY = "RAIL-CARRIERTRANSFERCANCELREPLY";
        public static string MESSAGENAME_RAIL_TRANSFERCANCELFAILED = "RAIL-TRANSFERCANCELFAILED";
        public static string MESSAGENAME_RAIL_PORTINSERVICE = "RAIL-PORTINSERVICE";
        public static string MESSAGENAME_RAIL_PORTOUTOFSERVICE = "RAIL-PORTOUTOFSERVICE";
        public static string MESSAGENAME_RAILSTORAGE_ONLINECONNECTED = "RAILSTORAGE-ONLINECONNECTED";
        public static string MESSAGENAME_RAILSTORAGE_ONLINEDISCONNECTED = "RAILSTORAGE-ONLINEDISCONNECTED";
        public static string MESSAGENAME_RAILSTORAGE_MESSAGERECEIVED = "RAILSTORAGE-MESSAGERECEIVED";
        public static string MESSAGENAME_RAILSTORAGE_CARRIERINSTALL = "RAILSTORAGE-CARRIERINSTALL";
        public static string MESSAGENAME_RAILSTORAGE_CARRIERINSTALLLIST = "RAILSTORAGE-CARRIERINSTALLLIST";
        public static string MESSAGENAME_RAILSTORAGE_CARRIERINSTALLED = "RAILSTORAGE-CARRIERINSTALLED";
        public static string MESSAGENAME_RAILSTORAGE_CARRIERREMOVE = "RAILSTORAGE-CARRIERREMOVE";
        public static string MESSAGENAME_RAILSTORAGE_CARRIERREMOVED = "RAILSTORAGE-CARRIERREMOVED";
        public static string MESSAGENAME_RAILSTORAGE_INVENTORYREQUEST = "RAILSTORAGE-INVENTORYREQUEST";
        public static string MESSAGENAME_RAILSTORAGE_STATEREQUEST = "RAILSTORAGE-STATEREQUEST";
        public static string MESSAGENAME_RAILSTORAGE_IDREAD = "RAILSTORAGE-IDREAD";
        public static string MESSAGENAME_RAILSTORAGE_IDREADLIST = "RAILSTORAGE-IDREADLIST";
        public static string MESSAGENAME_RAILSTORAGE_PAUSE = "RAILSTORAGE-PAUSE";
        public static string MESSAGENAME_RAILSTORAGE_RESUME = "RAILSTORAGE-RESUME";
        public static string MESSAGENAME_RAILSTORAGE_OFFLINE = "RAILSTORAGE-OFFLINE";
        public static string MESSAGENAME_RAILSTORAGE_ONLINELOCAL = "RAILSTORAGE-ONLINELOCAL";
        public static string MESSAGENAME_RAILSTORAGE_ONLINEREMOTE = "RAILSTORAGE-ONLINEREMOTE";
        public static string MESSAGENAME_RAILSTORAGE_DATETIMESET = "RAILSTORAGE-DATETIMESET";
        public static string MESSAGENAME_RAILSTORAGE_INFORM = "RAILSTORAGE-INFORM";
        public static string MESSAGENAME_RAILSTORAGE_PORTOCCUPIEDCHANGE = "RAILSTORAGE-PORTOCCUPIEDCHANGE";
        public static string MESSAGENAME_RAILSTORAGE_PORTINSERVICE = "RAILSTORAGE-PORTINSERVICE";
        public static string MESSAGENAME_RAILSTORAGE_PORTOUTOFSERVICE = "RAILSTORAGE-PORTOUTOFSERVICE";
        public static string MESSAGENAME_PROCESS_ONLINECONNECTED = "PROCESS-ONLINECONNECTED";
        public static string MESSAGENAME_PROCESS_ONLINEDISCONNECTED = "PROCESS-ONLINEDISCONNECTED";
        public static string MESSAGENAME_PROCESS_MESSAGERECEIVED = "PROCESS-MESSAGERECEIVED";
        public static string MESSAGENAME_PROCESS_PORTOCCUPIEDCHANGE = "PROCESS-PORTOCCUPIEDCHANGE";
        public static string MESSAGENAME_UI_SEARCHROUTE = "UI-SEARCHROUTE";
        public static string MESSAGENAME_UI_TRANSPORT = "UI-TRANSPORT";
        public static string MESSAGENAME_UI_TRANSPORT_DELETE = "UI-TRANSPORT-DELETE";
        public static string MESSAGENAME_UI_UNIT_PORT = "UI-UNIT-PORT";
        public static string MESSAGENAME_COMMON_TEST = "COMMON-TEST";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT = "COMMON-CARRIERTRANSPORT";
        public static string MESSAGENAME_COMMON_SECSABORTMESSAGE = "COMMON-SECSABORTMESSAGE";
        public static string MESSAGENAME_COMMON_SECSINVALIDMESSAGE = "COMMON-SECSINVALIDMESSAGE";
        public static string MESSAGENAME_COMMON_SECSUNKNOWNMESSAGE = "COMMON-SECSUNKNOWNMESSAGE";
        public static string MESSAGENAME_COMMON_SECSTIMEOUT = "COMMON-SECSTIMEOUT";
        public static string MESSAGENAME_ENHANCEDPORTS_REPORTUNITSTATECHANGED = "ENHANCEDPORTS-REPORTUNITSTATECHANGED";

        public static string MESSAGENAME_COMMON_AWAKE = "COMMON-AWAKE";

        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_ALTERNATE = "COMMON-SCHEDULING-AWAKE-ALTERNATE";
        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_ALTERNATED = "COMMON-SCHEDULING-AWAKE-ALTERNATED";
        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_CREATED = "COMMON-SCHEDULING-AWAKE-CREATED";
        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_PAUSED = "COMMON-SCHEDULING-AWAKE-PAUSED";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT_AWAKE = "COMMON-CARRIERTRANSPORT-AWAKE";

        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_RECOVERY = "COMMON-SCHEDULING-AWAKE-RECOVERY";
        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_RECOVERY_ALL = "COMMON-SCHEDULING-AWAKE-RECOVERY-ALL";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT_RECOVERY = "COMMON-CARRIERTRANSPORT-RECOVERY";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT_BATCH = "COMMON-CARRIERTRANSPORT-BATCH";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT_DELETE = "COMMON-CARRIERTRANSPORT-DELETE";

        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_RETRANSPORT = "COMMON-SCHEDULING-AWAKE-RETRANSPORT";
        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_RETRANSPORT_ALL = "COMMON-SCHEDULING-AWAKE-RETRANSPORT-ALL";
        public static string MESSAGENAME_COMMON_SCHEDULING_EMPTYCARRIERBALANCE = "COMMON_SCHEDULING_EMPTYCARRIERBALANCE";
        public static string MESSAGENAME_COMMON_CARRIERTRANSPORT_RETRANSPORT = "COMMON-CARRIERTRANSPORT-RETRANSPORT";
        public static string MESSAGENAME_COMMON_TRANSPORTCOMMANDS_STOP = "COMMON-TRANSPORTCOMMANDS-STOP";

        public static string MESSAGENAME_COMMON_SCHEDULING_DELETE_ALTERNATE = "COMMON-SCHEDULING-DELETE-ALTERNATE";
        public static string MESSAGENAME_COMMON_SCHEDULING_DELETE_ALTERNATED = "COMMON-SCHEDULING-DELETE-ALTERNATED";
        public static string MESSAGENAME_COMMON_SCHEDULING_DELETE_GARBAGETRANSPORTJOB = "COMMON-SCHEDULING-DELETE-GARBAGETRANSPORTJOB";
        public static string MESSAGENAME_COMMON_SCHEDULING_DELETE_GARBAGETRANSPORTCOMMAND = "COMMON-SCHEDULING-DELETE-GARBAGETRANSPORTCOMMAND";
        public static string MESSAGENAME_COMMON_SCHEDULING_DELETE_GARBAGE = "COMMON-SCHEDULING-DELETE-GARBAGE";
        public static string MESSAGENAME_COMMON_SCHEDULING_PRIORITY_BOOSTUP = "COMMON-SCHEDULING-PRIORITY-BOOSTUP";
        public static string MESSAGENAME_COMMON_SENDPORTINOUTTYPECHANGE = "COMMON-SENDPORTINOUTTYPECHANGE";
        public static string MESSAGENAME_COMMON_SENDTRANSFER = "COMMON-SEND-TRANSFER";
        public static string MESSAGENAME_COMMON_SCHEDULING = "COMMON-SCHEDULING";
        public static string MESSAGENAME_MASSSTORAGE_ENHANCEDCARRIERS_CARRIERSTORED = "MASSSTORAGE-ENHANCEDCARRIERS-CARRIERSTORED";
        public static string MESSAGENAME_MASSSTORAGE_ENHANCEDCARRIERS_CARRIERWAITOUT = "MASSSTORAGE-ENHANCEDCARRIERS-CARRIERWAITOUT";
        public static string MESSAGENAME_RAILSTORAGE_ENHANCEDCARRIERS_CARRIERINSTALLED = "RAILSTORAGE-ENHANCEDCARRIERS-CARRIERINSTALLED";
        public static string MESSAGENAME_ENHANCEDCARRIERS_CARRIERREMOVED = "ENHANCEDCARRIERS-CARRIERREMOVED";
        public static string MESSAGENAME_COMMON_ENHANCEDCARRIERS_FABDUPLICATED = "COMMON-ENHANCEDCARRIERS-FABDUPLICATED";
        public static string MESSAGENAME_MASSSTORAGE_ENHANCEDTRANSFERS_TRANSFERCOMPLETED = "MASSSTORAGE-ENHANCEDTRANSFERS-TRANSFERCOMPLETED";
        public static string MESSAGENAME_RAIL_ENHANCEDTRANSFERS_TRANSFERCOMPLETED = "RAIL-ENHANCEDTRANSFERS-TRANSFERCOMPLETED";
        public static string MESSAGENAME_RAILSTORAGE_ENHANCEDPORTS_BANNED = "RAILSTORAGE-ENHANCEDPORTS-BANNED";
        public static string MESSAGENAME_RAILSTORAGE_ENHANCEDPORTS_CREATEPORTS = "RAILSTORAGE-ENHANCEDPORTS-CREATEPORTS";

        public static string MESSAGENAME_COMMON_SCHEDULING_AWAKE_BIDIRECTIONALQUEUING = "COMMON-SCHEDULING-AWAKE-BIDIRECTIONALQUEUING";
        public static string MESSAGENAME_COMMON_START_TRANS = "COMMON-START-TRANS";
        public static string MESSAGENAME_COMMON_START_EI = "COMMON-START-EI";
        public static string MESSAGENAME_COMMON_START_DAEMON = "COMMON-START-DAEMON";
        public static string MESSAGENAME_COMMON_START_CONTROL = "COMMON-START-CONTROL";
        public static string MESSAGENAME_COMMON_START_EMULATOR = "COMMON-START-EMULATOR";
        public static string MESSAGENAME_COMMON_START_HOST = "COMMON-START-HOST";
        public static string MESSAGENAME_COMMON_START_REPORT = "COMMON-START-REPORT";
        public static string MESSAGENAME_COMMON_START_QUERY = "COMMON-START-QUERY";
        public static string MESSAGENAME_COMMON_STOP_TRANS = "COMMON-STOP-TRANS";
        public static string MESSAGENAME_COMMON_STOP_EI = "COMMON-STOP-EI";
        public static string MESSAGENAME_COMMON_STOP_DAEMON = "COMMON-STOP-DAEMON";
        public static string MESSAGENAME_COMMON_STOP_CONTROL = "COMMON-STOP-CONTROL";
        public static string MESSAGENAME_COMMON_STOP_EMULATOR = "COMMON-STOP-EMULATOR";
        public static string MESSAGENAME_COMMON_STOP_HOST = "COMMON-STOP-HOST";
        public static string MESSAGENAME_COMMON_STOP_REPORT = "COMMON-STOP-REPORT";
        public static string MESSAGENAME_COMMON_STOP_QUERY = "COMMON-STOP-QUERY";

        public static string MESSAGENAME_NANOTRANS_CARRIERTRANSFER = "NANOTRANS-CARRIERTRANSFER";
        public static string MESSAGENAME_NANOTRANS_CIRCULARTRANSFER = "NANOTRANS-CIRCULARTRANSFER";
        public static string MESSAGENAME_NANOTRANS_CHANGECARRIERINFORMATION = "NANOTRANS-CHANGECARRIERINFORMATION";
        public static string MESSAGENAME_NANOTRANS_CHANGEMACHINEINFORMATION = "NANOTRANS-CHANGEMACHINEINFORMATION";
        public static string MESSAGENAME_NANOTRANS_CHANGEUNITINFORMATION = "NANOTRANS-CHANGEUNITINFORMATION";
        public static string MESSAGENAME_NANOTRANS_CHANGEWATERMARK = "NANOTRANS-CHANGEWATERMARK";
        public static string MESSAGENAME_NANOTRANS_TRANSFERCANCEL = "NANOTRANS-TRANSFERCANCEL";
        public static string MESSAGENAME_NANOTRANS_TRANSPORTCOMMAND = "NANOTRANS-TRANSPORTCOMMAND";
        public static string MESSAGENAME_NANOTRANS_STAGECOMMAND = "NANOTRANS-STAGECOMMAND";
        public static string MESSAGENAME_NANOTRANS_PORTINOUTTYPECHANGE = "NANOTRANS-PORTINOUTTYPECHANGE";
        public static string MESSAGENAME_REQUEST_TRANSPORT = "REQUEST-TRANSPORT";
        public static string MESSAGENAME_HOST_EVENT_TS_STARTED = "HOST-EVENT-TS-STARTED";
        public static string MESSAGENAME_HOST_EVENT_TS_STOPPED = "HOST-EVENT-TS-STOPPED";
        public static string MESSAGENAME_HOST_EVENT_TS_ALL_STOPPED = "HOST-EVENT-TS-ALL-STOPPED";
        public static string MESSAGENAME_HOST_EVENT_ES_STARTED = "HOST-EVENT-ES-STARTED";
        public static string MESSAGENAME_HOST_EVENT_ES_STOPPED = "HOST-EVENT-ES-STOPPED";
        public static string MESSAGENAME_HOST_EVENT_CS_STARTED = "HOST-EVENT-CS-STARTED";
        public static string MESSAGENAME_HOST_EVENT_CS_STOPPED = "HOST-EVENT-CS-STOPPED";
        public static string MESSAGENAME_HOST_EVENT_DS_STARTED = "HOST-EVENT-DS-STARTED";
        public static string MESSAGENAME_HOST_EVENT_DS_STOPPED = "HOST-EVENT-DS-STOPPED";
        public static string MESSAGENAME_HOST_EVENT_BATCHTRANSPORTJOB_CREATED = "HOST-EVENT-BATCHTRANSPORTJOB-CREATED";
        public static string MESSAGENAME_HOST_EVENT_BATCHTRANSPORTJOB_COMPLETED = "HOST-EVENT-BATCHTRANSPORTJOB-COMPLETED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_CREATED = "HOST-EVENT-TRANSPORTJOB-CREATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_QUEUING = "HOST-EVENT-TRANSPORTJOB-QUEUING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_WAITING = "HOST-EVENT-TRANSPORTJOB-WAITING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_INITIATED = "HOST-EVENT-TRANSPORTJOB-INITIATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_TRANSFERRING = "HOST-EVENT-TRANSPORTJOB-TRANSFERRING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_COMPLETED = "HOST-EVENT-TRANSPORTJOB-COMPLETED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_TERMINATED = "HOST-EVENT-TRANSPORTJOB-TERMINATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_FAILED = "HOST-EVENT-TRANSPORTJOB-FAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_ALTERNATING = "HOST-EVENT-TRANSPORTJOB-ALTERNATING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_ALTERNATED = "HOST-EVENT-TRANSPORTJOB-ALTERNATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_ABORTING = "HOST-EVENT-TRANSPORTJOB-ABORTING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_ABORTED = "HOST-EVENT-TRANSPORTJOB-ABORTED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_ABORTFAILED = "HOST-EVENT-TRANSPORTJOB-ABORTFAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_CANCELING = "HOST-EVENT-TRANSPORTJOB-CANCELING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_CANCELED = "HOST-EVENT-TRANSPORTJOB-CANCELED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_CANCELFAILED = "HOST-EVENT-TRANSPORTJOB-CANCELFAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_DESTCHANGED = "HOST-EVENT-TRANSPORTJOB-DESTCHANGED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTJOB_DESTCHANGEFAILED = "HOST-EVENT-TRANSPORTJOB-DESTCHANGEFAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CREATED = "HOST-EVENT-TRANSPORTCMD-CREATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_QUEUING = "HOST-EVENT-TRANSPORTCMD-QUEUING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_QUEUED = "HOST-EVENT-TRANSPORTCMD-QUEUED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_WAITING = "HOST-EVENT_TRANSPORTCMD-WAITING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_INITIATED = "HOST-EVENT-TRANSPORTCMD-INITIATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_TRANSFERRING = "HOST-EVENT-TRANSPORTCMD-TRANSFERRING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_COMPLETED = "HOST-EVENT-TRANSPORTCMD-COMPLETED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_FAILED = "HOST-EVENT-TRANSPORTCMD-FAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_PAUSED = "HOST-EVENT-TRANSPORTCMD-PAUSED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_RESUMED = "HOST-EVENT-TRANSPORTCMD-RESUMED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_ABORTING = "HOST-EVENT-TRANSPORTCMD-ABORTING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_ABORTRESERVED = "HOST-EVENT-TRANSPORTCMD-ABORTRESERVED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_ABORTINITIATED = "HOST-EVENT-TRANSPORTCMD-ABORTINITIATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_ABORTCOMPLETED = "HOST-EVENT-TRANSPORTCMD-ABORTCOMPLETED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_ABORTFAILED = "HOST-EVENT-TRANSPORTCMD-ABORTFAILED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CANCELING = "HOST-EVENT-TRANSPORTCMD-CANCELING";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CANCELRESERVED = "HOST-EVENT-TRANSPORTCMD-CANCELRESERVED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CANCELINITIATED = "HOST-EVENT-TRANSPORTCMD-CANCELINITIATED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CANCELCOMPLETED = "HOST-EVENT-TRANSPORTCMD-CANCELCOMPLETED";
        public static string MESSAGENAME_HOST_EVENT_TRANSPORTCMD_CANCELFAILED = "HOST-EVENT-TRANSPORTCMD-CANCELFAILED";
        public static string MESSAGENAME_HOST_EVENT_FIRSTTRANSPORTCMD_QUEUED = "HOST-EVENT-FIRSTTRANSPORTCMD-QUEUED";
        public static string MESSAGENAME_HOST_EVENT_FIRSTTRANSPORTCMD_FAILED = "HOST-EVENT-FIRSTTRANSPORTCMD-FAILED";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_LOCATION = "HOST-EVENT-CARRIER-LOCATION";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_INSTALLED = "HOST-EVENT-CARRIER-INSTALLED";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_INSTALLFAILED = "HOST-EVENT-CARRIER-INSTALLFAILED";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_REMOVED = "HOST-EVENT-CARRIER-REMOVED";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_EVICTED = "HOST-EVENT-CARRIER-EVICTED";
        public static string MESSAGENAME_HOST_EVENT_CARRIER_REMOVEFAILED = "HOST-EVENT-CARRIER-REMOVEFAILED";
        public static string MESSAGENAME_HOST_EVENT_INVENTORY_CARRIERS = "HOST-EVENT-INVENTORY-CARRIERS";
        public static string MESSAGENAME_HOST_EVENT_ALARM_STATECHANGED = "HOST-EVENT-ALARM-STATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_ALARM_SET = "HOST-EVENT-ALARM-SET";
        public static string MESSAGENAME_HOST_EVENT_ALARM_CLEARED = "HOST-EVENT-ALARM-CLEARED";
        public static string MESSAGENAME_HOST_EVENT_ALARM_REPORT = "HOST-EVENT-ALARM-REPORT";
        public static string MESSAGENAME_HOST_EVENT_UNITALARM_SET = "HOST-EVENT-UNITALARM-SET";
        public static string MESSAGENAME_HOST_EVENT_UNITALARM_CLEARED = "HOST-EVENT-UNITALARM-CLEARED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_ONLINECONNECTED = "HOST-EVENT-MACHINE-ONLINECONNECTED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_ONLINEDISCONNECTED = "HOST-EVENT-MACHINE-ONLINEDISCONNECTED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_STATECHANGED = "HOST-EVENT-MACHINE-STATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_CONTROLSTATECHANGED = "HOST-EVENT-MACHINE-CONTROLSTATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_TSCSTATECHANGED = "HOST-EVENT-MACHINE-TSCSTATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_RECONCILESTARTED = "HOST-EVENT_MACHINE-RECONCILESTARTED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_RECONCILECOMPLETED = "HOST-EVENT-MACHINE-RECONCILECOMPLETED";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_FULLSET = "HOST-EVENT-MACHINE-FULLSET";
        public static string MESSAGENAME_HOST_EVENT_MACHINE_FULLRELEASE = "HOST-EVENT-MACHINE-FULLRELEASE";
        public static string MESSAGENAME_HOST_EVENT_UNIT_STATECHANGED = "HOST-EVENT-UNIT-STATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_UNIT_SUBSTATECHANGED = "HOST-EVENT-UNIT-SUBSTATECHANGED";
        public static string MESSAGENAME_HOST_EVENT_PORT_INOUTTYPECHANGED = "HOST-EVENT-PORT-INOUTTYPECHANGED";
        public static string MESSAGENAME_HOST_EVENT_PORT_ACCESSMODECHANGED = "HOST-EVENT-PORT-ACCESSMODECHANGED";
        public static string MESSAGENAME_HOST_EVENT_PORT_OCCUPIEDCHANGED = "HOST-EVENT-PORT-OCCUPIEDCHANGED";
        public static string MESSAGENAME_HOST_EVENT_ZONECAPACITY_CHANGED = "HOST-EVENT-ZONECAPACITY-CHANGED";
        public static string MESSAGENAME_HOST_EVENT_INVENTORY_ZONES = "HOST-EVENT-INVENTORY-ZONES";
        public static string MESSAGENAME_HOST_REPLY_BATCHTRANSPORTJOBREQUEST = "HOST-REPLY-BATCHTRANSPORTJOB-REQUEST";
        public static string MESSAGENAME_HOST_REPLY_TRANSPORTJOBREQUEST = "HOST-REPLY-TRANSPORTJOB-REQUEST";
        public static string MESSAGENAME_HOST_REPLY_TRANSPORTJOBCANCEL = "HOST-REPLY-TRANSPORTJOB-CANCELREQUEST";
        public static string MESSAGENAME_HOST_REPLY_DESTCHANGE = "HOST-REPLY-TRANSPORTJOB-DESTCHANGEREQUEST";
        public static string MESSAGENAME_HOST_REPLY_CARRIERDATA = "HOST-REPLY-CARRIER-DATAREQUEST";
        public static string MESSAGENAME_HOST_REPLY_INVENTORYCARRIERS = "HOST-REPLY-INVENTORY-CARRIERREQUEST";
        public static string MESSAGENAME_HOST_REPLY_INVENTORYZONES = "HOST-REPLY-INVENTORY-ZONEREQUEST";
        public static string MESSAGENAME_HOST_REPLY_MACHINESTATE = "HOST-REPLY-MACHINE-STATEREQUEST";
        public static string MESSAGENAME_HOST_REPLY_MACHINECONTROLSTATE = "HOST-REPLY-MACHINE-CONTROLSTATEREQUEST";
        public static string MESSAGENAME_HOST_REPLY_MCSSTATEREQUEST = "HOST-REPLY-MCS-STATEREQUEST";
        public static string MESSAGENAME_HOST_REQUEST_TRANSPORTDESTREQUEST = "HOST-REQUEST-TRANSPORTJOB-DESTREQUEST";
        public static string MESSAGENAME_HOST_COMMAND_TRANSPORTJOBREQEUST = "HOST-COMMAND-TRANSPORTJOB-REQUEST";
        public static string MESSAGENAME_HOST_COMMAND_DESTCHANGE = "HOST-COMMAND-TRANSPORTJOB-DESTCHANGE";
        public static string MESSAGENAME_INTERFAB_CARRIERARRIVED = "INTERFAB-CARRIERARRIVED";
        public static string MESSAGENAME_INTERFAB_MOVECARRIER = "INTERFAB-MOVECARRIER";
        public static string MESSAGENAME_INTERFAB_SENDSTAGE = "INTERFAB-SENDSTAGE";
        public static string MESSAGENAME_INTERFAB_PORTCAPACITY = "INTERFAB-PORTCAPACITY";
        public static string MESSAGENAME_INTERFAB_PORTSTATE = "INTERFAB-PORTSTATE";
        public static string MESSAGENAME_INTERFAB_ONLINECONNECTED = "INTERFAB-ONLINECONNECTED";
        public static string MESSAGENAME_INTERFAB_ONLINEDISCONNECTED = "INTERFAB-ONLINEDISCONNECTED";
        public static string MESSAGENAME_INTERFAB_MESSAGERECEIVED = "INTERFAB-MESSAGERECEIVED";
        public static string MESSAGENAME_COMMON_ENHANCEDPORTS_CREATEPORTHISTORY = "COMMON-ENHANCEDPORTS-CREATEPORTHISTORY";
        public static string MESSAGENAME_COMMON_ENHANCEDCARRIERS_CREATECARRIERLOCATIONHISTORY = "COMMON-ENHANCEDCARRIERS-CREATECARRIERLOCATIONHISTORY";
        public static string MESSAGENAME_COMMON_ENHANCEDALARMS_CREATEALARMREPORTHISTORY = "COMMON-ENHANCEDALARMS-CREATEALARMREPORTHISTORY";
        public static string MESSAGENAME_COMMON_SCHEDULING_GARBAGECARRIER_TRANSPORT_ON_RAILSTORAGEMACHINE = "COMMON-SCHEDULING-GARBAGECARRIER-TRANSPORT-ON-RAILSTORAGEMACHINE";

        private string carrierName;
        private string transportCommandId;
        private string currentUnitName;
        private string currentType;
        private string currentContainerName;
        private string currentSlotNumber;

        public string CarrierName { get { return carrierName; } set { carrierName = value; } }
        public string TransportCommandId { get { return transportCommandId; } set { transportCommandId = value; } }

        public string CurrentUnitName { get { return currentUnitName; } set { currentUnitName = value; } }
        public string CurrentType { get { return currentType; } set { currentType = value; } }
        public string CurrentContainerName { get { return currentContainerName; } set { currentContainerName = value; } }

        public string CurrentSlotNumber { get { return currentSlotNumber; } set { currentSlotNumber = value; } }

        public Carrier Carrier { get; set; }
        public Lot Lot { get; set; }
        public TransportCommand TransportCommand { get; set; }
        public Unit CurrentUnit { get; set; }
        public MultiPosition MultiPosition { get; set; }
        public TransportJob TransportJob { get; set; }
        //public BatchTransportJob BatchTransportJob { get; set; }
        public Machine CurrentTransportMachine { get; set; }
        public Machine DestTransportMachine { get; set; }
        public bool PossibleToTransfer { get; set; }

        public RouteInfo RouteInfo { get; set; }
        public Route.Model.Route BestRoute { get; set; }

        public bool DynamicWeight { get; set; }

        public bool ContainDeadNode { get; set; }

        public bool Alternate { get; set; }
        public AlternateStorage AlternateStorage { get; set; }
        public Machine AlternateMachine { get; set; }
        public Unit AlternateUnit { get; set; }
        public Zone AlternateZone { get; set; }

        public string AlternateType { get; set; }
        public bool ForeTransfer { get; set; }
        public Machine ForeTemporaryMachine { get; set; }
        public Unit ForeTemporaryUnit { get; set; }
        public Zone ForeTemporaryZone { get; set; }
        public string ForeTemporaryType { get; set; }
        public IList CarrierProcessTypeNames { get; set; }
        public bool UseCarrierProcessType { get; set; }
        public BidirectionalNode UseBidirectionalNode { get; set; }

        public void ClearCause()
        {
            logger.Info("cause{" + this.Cause + "} will be reset");
            this.Cause = "";
        }

        public void ChangeCause(string cause)
        {
            logger.Info("cause{" + this.Cause + "} will be changed to {" + cause + "}");
            this.Cause = cause;
        }


        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("message{");
            sb.Append("messageName=").Append(this.MessageName);
            sb.Append(", carrierName=").Append(this.CarrierName);
            sb.Append(", transportCommandId=").Append(this.TransportCommandId);
            sb.Append(", currentMachineName=").Append(this.CurrentMachineName);
            sb.Append(", currentUnitName=").Append(this.CurrentUnitName);
            sb.Append(", originatedType=").Append(this.OriginatedType);
            sb.Append(", originatedName=").Append(this.OriginatedName);
            sb.Append(", connectionId=").Append(this.ConnectionId);
            sb.Append(", userName=").Append(this.UserName);
            sb.Append(", possibleToTransfer=").Append(this.PossibleToTransfer);
            sb.Append(", containDeadNode=").Append(this.ContainDeadNode);
            sb.Append(", alternate=").Append(this.Alternate);
            sb.Append(", foreTransfer=").Append(this.ForeTransfer);
            sb.Append(", useCarrierProcessType=").Append(this.UseCarrierProcessType);
            sb.Append(", useBidirectionalNode=").Append(this.UseBidirectionalNode);
            sb.Append("}");
            return sb.ToString();
        }
    }
}
