using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ACS.Core.Path.Model;
using ACS.Core.Resource.Model;
using ACS.Core.Resource.Model.Factory.Machine;
using ACS.Core.Resource.Model.Factory.Zone;
using ACS.Core.Resource.Model.Factory.Unit;
using System.Collections;

namespace ACS.Core.Resource
{
    public interface IResourceManagerEx
    {
        void CreateInform(Inform paramInform);
        void UpdateInform(Inform paramInform);
        int DeleteUIInform(DateTime paramDate);
        int DeleteUIInform(string paramString);
        IList GetUIInformBySource(string paramString);
        IList GetUIInformByMessage(string paramString1, string paramString2);
        IList GetUIInformByDescription(string paramString1, string paramString2);
        void CreateBay(BayEx paramBay);
        BayEx GetBay(string paramString);
        IList GetBays();
        void UpdateBay(BayEx paramBay);
        void DeleteBay(BayEx paramBay);
        int DeleteBay(string paramString);
        void CreateLink(LinkEx paramLink);
        LinkEx GetLink(string paramString);
        IList GetLinks();
        void UpdateLink(LinkEx paramLink);
        void DeleteLink(LinkEx paramLink);
        int DeleteLink(string paramString);
        void CreateLocation(LocationEx paramLocation);
        LocationEx GetLocation(string paramString);
        LocationEx GetLocationByLocationId(string paramString);
        LocationEx GetLocationByStationId(string paramString);
        IList GetLocations();
        bool CheckLocation(string paramString);
        void UpdateLocation(LocationEx paramLocation);
        void DeleteLocation(LocationEx paramLocation);
        int DeleteLocation(string paramString);
        void CreateNode(NodeEx paramNode);
        NodeEx GetNode(string paramString);
        IList GetNodes();
        IList GetNodesByType(string paramString);
        void UpdateNode(NodeEx paramNode);
        int DeleteNode(string paramString);
        void CreateStation(StationEx paramStation);
        StationEx GetStation(string paramString);
        IList GetStations();
        StationEx GetStationByLinkId(string paramString);
        void UpdateStation(StationEx paramStation);
        void DeleteStation(StationEx paramStation);
        int DeleteStation(string paramString);
        void CreateVehicle(VehicleEx paramVehicle);
        VehicleEx GetVehicle(string paramString);
        VehicleEx GetVehicleByCurrentNode(string paramString);
        IList GetVehicles();
        IList GetVehiclesByBayId(string paramString);
        IList GetVehiclesByCurrentNode(string paramString);
        int UpdateVehicle(VehicleEx paramVehicle, string paramString, object paramObject);
        void UpdateVehicle(VehicleEx paramVehicle);
        int UpdateVehicleBatch(VehicleEx paramVehicle, IDictionary<string, object> fieldChanges, string messageName, bool createHistory);
        /// <summary>
        /// race condition 방지용 conditional UPDATE. ProcessingState=IDLE이면서
        /// TransportCommandId가 비어있을 때만 차량을 단일 SQL로 ASSIGN 상태로 전이한다.
        /// 성공 시 NA_H_VEHICLE에 history 1건 기록. 실패(0행)면 false.
        /// </summary>
        bool TryAssignVehicleAtomic(string vehicleId, string transportCommandId, string messageName);
        int UpdateVehicleTransferState(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleTransferState(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleTransferState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleTransferState(string paramString1, string paramString2);
        int UpdateVehicleLocation(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleLocation(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleLocation(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleLocation(string paramString1, string paramString2);
        int UpdateVehicleBatteryRate(VehicleEx paramVehicle, int paramInt);
        int UpdateVehicleBatteryRate(string paramString, int paramInt);
        int UpdateVehicleTransportCommandId(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleTransportCommandId(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleTransportCommandId(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleTransportCommandId(string paramString1, string paramString2);
        int UpdateVehicleProcessingState(VehicleEx paramVehicleACS, string paramString1, string paramString2);
        int UpdateVehicleProcessingState(VehicleEx paramVehicleACS, string paramString);
        int UpdateVehicleProcessingState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleProcessingState(string paramString1, string paramString2);
        int UpdateVehicleConnectionState(VehicleEx paramVehicle, string paramString1, string paramString2);  
        int UpdateVehicleConnectionState(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleConnectionState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleConnectionState(string paramString1, string paramString2);
        int UpdateVehicleRunState(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleRunState(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleRunState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleRunState(string paramString1, string paramString2);
        int UpdateVehicleFullState(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleFullState(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleFullState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleFullState(string paramString1, string paramString2);
        int UpdateVehicleNodeCheckTime(VehicleEx paramVehicle);
        int UpdateVehicleNodeCheckTime(string paramString);
        int UpdateVehicleEventTime(VehicleEx paramVehicle);
        int UpdateVehicleEventTime(string paramString);
        int UpdateVehicleAlarmState(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleAlarmState(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleAlarmState(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleAlarmState(string paramString1, string paramString2);
        int UpdateVehicleBatteryVoltage(VehicleEx paramVehicle, float paramFloat);
        int UpdateVehicleBatteryVoltage(string paramString, float paramFloat);
        int UpdateVehicleMainboardVersion(string paramString1, string paramString2);
        int UpdateVehiclePlcVersion(string paramString1, string paramString2);
        int UpdateVehicleAcsDestNodeId(VehicleEx paramVehicle, string paramString1, string paramString2);
        int UpdateVehicleAcsDestNodeId(VehicleEx paramVehicle, string paramString);
        int UpdateVehicleAcsDestNodeId(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleAcsDestNodeId(string paramString1, string paramString2);
        int UpdateVehicleVehicleDestNodeId(VehicleEx paramVehicleACS, string paramString1, string paramString2);
        int UpdateVehicleVehicleDestNodeId(VehicleEx paramVehicleACS, string paramString);
        int UpdateVehicleVehicleDestNodeId(string paramString1, string paramString2, string paramString3);
        int UpdateVehicleVehicleDestNodeId(string paramString1, string paramString2);
        void DeleteVehicle(VehicleEx paramVehicle);
        int DeleteVehicle(string paramString);
        void CreateZone(ZoneEx paramZone);
        ZoneEx GetZone(string paramString);
        IList GetZones();
        ZoneEx GetZoneByBayId(string paramString);
        void UpdateZone(ZoneEx paramZone);
        void DeleteZone(ZoneEx paramZone);
        int DeleteZone(string paramString);
        void CreateVehicleCrossWait(VehicleCrossWaitEx paramVehicleCrossWait);
        VehicleCrossWaitEx GetVehicleCrossWait(string paramString);
        VehicleCrossWaitEx GetVehicleCrossWaitByNodeId(string paramString);
        VehicleCrossWaitEx GetVehicleCrossWaitAllByNodeId(string paramString);
        IList GetVehiclesCrossWaitByNodeId(string paramString);
        IList GetVehiclesCrossWaitByNodeIdAndState(string paramString1, string paramString2);
        IList GetVehiclesCrossWaitByStateOrderbyCreateTime(string paramString);
        IList GetVehiclesCrossWaitAllOrderbyCreateTime();
        List<VehicleCrossWaitEx> GetVehiclesCrossWaitByStateAndBeforeTimeOrderbyCreateTime(string paramString, int paramInt);
        void UpdateVehicleCrossWait(VehicleCrossWaitEx paramVehicleCrossWait);
        int UpdateVehicleCrossWait(VehicleCrossWaitEx paramVehicleCrossWait, Dictionary<string, object> paramDictionary);
        void DeleteVehicleCrossWait(VehicleCrossWaitEx paramVehicleCrossWait);
        int DeleteVehicleCrossWait(string paramString);
        int DeleteVehicleCrossWait(DateTime paramDateTime);
        int DeleteVehicleCrossWait(DateTime paramDate, string paramString);
        string GetBayIdByStationId(string paramString);
        string GetBayIdByLocationId(string paramString);
        LinkZoneEx GetLinkZoneByLinkId(string paramString);
        IList GetLinkZonesByLinkId(string paramString);
        IList GetLinkZonesByZoneId(string paramString);
        IList GetLinkZonesByZoneIdTransferFlag(string paramString1, string paramString2);
        void CreateLinkZone(LinkZoneEx paramLinkZone);
        void DeleteLinkZone(LinkZoneEx paramLinkZone);
        int DeleteLinkZone(string paramString);
        IList GetLinkZones();
        Machine GetMachineByName(string machineName);
        Unit GetUnitByName(string unitName, string machineName);
        int UpdateVehicleState(VehicleEx vehicle, String State, String messageName);
        int UpdateVehicleState(String vehicleId, String State, String messageName);

    }
}
